package main

import "text/template"

var retryingQuerierTemplate = template.Must(template.New("retrying querier").Parse(`// Code generated by generate-sqlc-retrier. DO NOT EDIT.

package sqlc

{{- if .Imports }}
import (
{{- range .Imports }}
	{{ if .Name }}{{ .Name }} {{ end }}{{ printf "%q" .Path }}
{{- end }}
)
{{ end }}
type QueryRetrier interface {
	RetryQuery(ctx context.Context, operationName string, fn func() error) error
}

type retryingQuerier struct {
	next    Querier
	retrier QueryRetrier
}

func NewRetryingQuerier(next Querier, retrier QueryRetrier) Querier {
	return &retryingQuerier{next: next, retrier: retrier}
}

var _ Querier = (*retryingQuerier)(nil)
{{ range .Methods }}
func (q *retryingQuerier) {{ .Name }}{{ .Signature }} {
{{- if .ErrorOnly }}
	return q.retrier.RetryQuery({{ .ContextArg }}, {{ printf "%q" .Name }}, func() error {
		return q.next.{{ .Name }}({{ .CallArgs }})
	})
{{- else }}
	var result {{ .ResultType }}
	err := q.retrier.RetryQuery({{ .ContextArg }}, {{ printf "%q" .Name }}, func() error {
		callResult, callErr := q.next.{{ .Name }}({{ .CallArgs }})
		if callErr == nil {
			result = callResult
		}
		return callErr
	})
	return result, err
{{- end }}
}
{{ end }}`))
