// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mock UpdateScheduler,TelemetryDataStore,MinerGetter,CachedMinerGetter
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	interfaces "github.com/block/proto-fleet/server/internal/domain/miner/interfaces"
	models "github.com/block/proto-fleet/server/internal/domain/telemetry/models"
	models0 "github.com/block/proto-fleet/server/internal/domain/telemetry/models/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateScheduler is a mock of UpdateScheduler interface.
type MockUpdateScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateSchedulerMockRecorder
	isgomock struct{}
}

// MockUpdateSchedulerMockRecorder is the mock recorder for MockUpdateScheduler.
type MockUpdateSchedulerMockRecorder struct {
	mock *MockUpdateScheduler
}

// NewMockUpdateScheduler creates a new mock instance.
func NewMockUpdateScheduler(ctrl *gomock.Controller) *MockUpdateScheduler {
	mock := &MockUpdateScheduler{ctrl: ctrl}
	mock.recorder = &MockUpdateSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateScheduler) EXPECT() *MockUpdateSchedulerMockRecorder {
	return m.recorder
}

// AddDevices mocks base method.
func (m *MockUpdateScheduler) AddDevices(ctx context.Context, devices ...models.Device) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range devices {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDevices indicates an expected call of AddDevices.
func (mr *MockUpdateSchedulerMockRecorder) AddDevices(ctx any, devices ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, devices...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).AddDevices), varargs...)
}

// AddFailedDevices mocks base method.
func (m *MockUpdateScheduler) AddFailedDevices(ctx context.Context, devices ...models.Device) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range devices {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddFailedDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFailedDevices indicates an expected call of AddFailedDevices.
func (mr *MockUpdateSchedulerMockRecorder) AddFailedDevices(ctx any, devices ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, devices...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFailedDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).AddFailedDevices), varargs...)
}

// AddNewDevices mocks base method.
func (m *MockUpdateScheduler) AddNewDevices(ctx context.Context, deviceID ...models.DeviceIdentifier) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range deviceID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddNewDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewDevices indicates an expected call of AddNewDevices.
func (mr *MockUpdateSchedulerMockRecorder) AddNewDevices(ctx any, deviceID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, deviceID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).AddNewDevices), varargs...)
}

// FetchDevices mocks base method.
func (m *MockUpdateScheduler) FetchDevices(ctx context.Context, after time.Time) ([]models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDevices", ctx, after)
	ret0, _ := ret[0].([]models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDevices indicates an expected call of FetchDevices.
func (mr *MockUpdateSchedulerMockRecorder) FetchDevices(ctx, after any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).FetchDevices), ctx, after)
}

// IsFailedDevice mocks base method.
func (m *MockUpdateScheduler) IsFailedDevice(ctx context.Context, deviceID models.DeviceIdentifier) (bool, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFailedDevice", ctx, deviceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IsFailedDevice indicates an expected call of IsFailedDevice.
func (mr *MockUpdateSchedulerMockRecorder) IsFailedDevice(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFailedDevice", reflect.TypeOf((*MockUpdateScheduler)(nil).IsFailedDevice), ctx, deviceID)
}

// RemoveDevices mocks base method.
func (m *MockUpdateScheduler) RemoveDevices(ctx context.Context, deviceID ...models.DeviceIdentifier) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range deviceID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDevices indicates an expected call of RemoveDevices.
func (mr *MockUpdateSchedulerMockRecorder) RemoveDevices(ctx any, deviceID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, deviceID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).RemoveDevices), varargs...)
}

// MockTelemetryDataStore is a mock of TelemetryDataStore interface.
type MockTelemetryDataStore struct {
	ctrl     *gomock.Controller
	recorder *MockTelemetryDataStoreMockRecorder
	isgomock struct{}
}

// MockTelemetryDataStoreMockRecorder is the mock recorder for MockTelemetryDataStore.
type MockTelemetryDataStoreMockRecorder struct {
	mock *MockTelemetryDataStore
}

// NewMockTelemetryDataStore creates a new mock instance.
func NewMockTelemetryDataStore(ctrl *gomock.Controller) *MockTelemetryDataStore {
	mock := &MockTelemetryDataStore{ctrl: ctrl}
	mock.recorder = &MockTelemetryDataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelemetryDataStore) EXPECT() *MockTelemetryDataStoreMockRecorder {
	return m.recorder
}

// GetCombinedMetrics mocks base method.
func (m *MockTelemetryDataStore) GetCombinedMetrics(ctx context.Context, query models.CombinedMetricsQuery) (models.CombinedMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCombinedMetrics", ctx, query)
	ret0, _ := ret[0].(models.CombinedMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCombinedMetrics indicates an expected call of GetCombinedMetrics.
func (mr *MockTelemetryDataStoreMockRecorder) GetCombinedMetrics(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCombinedMetrics", reflect.TypeOf((*MockTelemetryDataStore)(nil).GetCombinedMetrics), ctx, query)
}

// GetLatestDeviceMetricsBatch mocks base method.
func (m *MockTelemetryDataStore) GetLatestDeviceMetricsBatch(ctx context.Context, deviceIDs []models.DeviceIdentifier) (map[models.DeviceIdentifier]models0.DeviceMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestDeviceMetricsBatch", ctx, deviceIDs)
	ret0, _ := ret[0].(map[models.DeviceIdentifier]models0.DeviceMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestDeviceMetricsBatch indicates an expected call of GetLatestDeviceMetricsBatch.
func (mr *MockTelemetryDataStoreMockRecorder) GetLatestDeviceMetricsBatch(ctx, deviceIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestDeviceMetricsBatch", reflect.TypeOf((*MockTelemetryDataStore)(nil).GetLatestDeviceMetricsBatch), ctx, deviceIDs)
}

// GetLatestFleetMetricRollupBucket mocks base method.
func (m *MockTelemetryDataStore) GetLatestFleetMetricRollupBucket(ctx context.Context) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestFleetMetricRollupBucket", ctx)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestFleetMetricRollupBucket indicates an expected call of GetLatestFleetMetricRollupBucket.
func (mr *MockTelemetryDataStoreMockRecorder) GetLatestFleetMetricRollupBucket(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestFleetMetricRollupBucket", reflect.TypeOf((*MockTelemetryDataStore)(nil).GetLatestFleetMetricRollupBucket), ctx)
}

// GetTimeSeriesTelemetry mocks base method.
func (m *MockTelemetryDataStore) GetTimeSeriesTelemetry(ctx context.Context, query models.TimeSeriesTelemetryQuery) ([]models0.DeviceMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeSeriesTelemetry", ctx, query)
	ret0, _ := ret[0].([]models0.DeviceMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeSeriesTelemetry indicates an expected call of GetTimeSeriesTelemetry.
func (mr *MockTelemetryDataStoreMockRecorder) GetTimeSeriesTelemetry(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeSeriesTelemetry", reflect.TypeOf((*MockTelemetryDataStore)(nil).GetTimeSeriesTelemetry), ctx, query)
}

// InsertMinerStateSnapshot mocks base method.
func (m *MockTelemetryDataStore) InsertMinerStateSnapshot(ctx context.Context, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMinerStateSnapshot", ctx, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMinerStateSnapshot indicates an expected call of InsertMinerStateSnapshot.
func (mr *MockTelemetryDataStoreMockRecorder) InsertMinerStateSnapshot(ctx, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMinerStateSnapshot", reflect.TypeOf((*MockTelemetryDataStore)(nil).InsertMinerStateSnapshot), ctx, at)
}

// Ping mocks base method.
func (m *MockTelemetryDataStore) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockTelemetryDataStoreMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockTelemetryDataStore)(nil).Ping), ctx)
}

// StoreDeviceMetrics mocks base method.
func (m *MockTelemetryDataStore) StoreDeviceMetrics(ctx context.Context, data ...models0.DeviceMetrics) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range data {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StoreDeviceMetrics", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreDeviceMetrics indicates an expected call of StoreDeviceMetrics.
func (mr *MockTelemetryDataStoreMockRecorder) StoreDeviceMetrics(ctx any, data ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, data...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreDeviceMetrics", reflect.TypeOf((*MockTelemetryDataStore)(nil).StoreDeviceMetrics), varargs...)
}

// StreamTelemetryUpdates mocks base method.
func (m *MockTelemetryDataStore) StreamTelemetryUpdates(ctx context.Context, query models.StreamQuery) (<-chan models.TelemetryUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamTelemetryUpdates", ctx, query)
	ret0, _ := ret[0].(<-chan models.TelemetryUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamTelemetryUpdates indicates an expected call of StreamTelemetryUpdates.
func (mr *MockTelemetryDataStoreMockRecorder) StreamTelemetryUpdates(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamTelemetryUpdates", reflect.TypeOf((*MockTelemetryDataStore)(nil).StreamTelemetryUpdates), ctx, query)
}

// UpsertFleetMetricRollups mocks base method.
func (m *MockTelemetryDataStore) UpsertFleetMetricRollups(ctx context.Context, startTime, endTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFleetMetricRollups", ctx, startTime, endTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFleetMetricRollups indicates an expected call of UpsertFleetMetricRollups.
func (mr *MockTelemetryDataStoreMockRecorder) UpsertFleetMetricRollups(ctx, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFleetMetricRollups", reflect.TypeOf((*MockTelemetryDataStore)(nil).UpsertFleetMetricRollups), ctx, startTime, endTime)
}

// MockMinerGetter is a mock of MinerGetter interface.
type MockMinerGetter struct {
	ctrl     *gomock.Controller
	recorder *MockMinerGetterMockRecorder
	isgomock struct{}
}

// MockMinerGetterMockRecorder is the mock recorder for MockMinerGetter.
type MockMinerGetterMockRecorder struct {
	mock *MockMinerGetter
}

// NewMockMinerGetter creates a new mock instance.
func NewMockMinerGetter(ctrl *gomock.Controller) *MockMinerGetter {
	mock := &MockMinerGetter{ctrl: ctrl}
	mock.recorder = &MockMinerGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinerGetter) EXPECT() *MockMinerGetterMockRecorder {
	return m.recorder
}

// GetMinerFromDeviceIdentifier mocks base method.
func (m *MockMinerGetter) GetMinerFromDeviceIdentifier(ctx context.Context, deviceIdentifier models.DeviceIdentifier) (interfaces.Miner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerFromDeviceIdentifier", ctx, deviceIdentifier)
	ret0, _ := ret[0].(interfaces.Miner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerFromDeviceIdentifier indicates an expected call of GetMinerFromDeviceIdentifier.
func (mr *MockMinerGetterMockRecorder) GetMinerFromDeviceIdentifier(ctx, deviceIdentifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerFromDeviceIdentifier", reflect.TypeOf((*MockMinerGetter)(nil).GetMinerFromDeviceIdentifier), ctx, deviceIdentifier)
}

// MockCachedMinerGetter is a mock of CachedMinerGetter interface.
type MockCachedMinerGetter struct {
	ctrl     *gomock.Controller
	recorder *MockCachedMinerGetterMockRecorder
	isgomock struct{}
}

// MockCachedMinerGetterMockRecorder is the mock recorder for MockCachedMinerGetter.
type MockCachedMinerGetterMockRecorder struct {
	mock *MockCachedMinerGetter
}

// NewMockCachedMinerGetter creates a new mock instance.
func NewMockCachedMinerGetter(ctrl *gomock.Controller) *MockCachedMinerGetter {
	mock := &MockCachedMinerGetter{ctrl: ctrl}
	mock.recorder = &MockCachedMinerGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCachedMinerGetter) EXPECT() *MockCachedMinerGetterMockRecorder {
	return m.recorder
}

// GetMinerFromDeviceIdentifier mocks base method.
func (m *MockCachedMinerGetter) GetMinerFromDeviceIdentifier(ctx context.Context, deviceIdentifier models.DeviceIdentifier) (interfaces.Miner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerFromDeviceIdentifier", ctx, deviceIdentifier)
	ret0, _ := ret[0].(interfaces.Miner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerFromDeviceIdentifier indicates an expected call of GetMinerFromDeviceIdentifier.
func (mr *MockCachedMinerGetterMockRecorder) GetMinerFromDeviceIdentifier(ctx, deviceIdentifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerFromDeviceIdentifier", reflect.TypeOf((*MockCachedMinerGetter)(nil).GetMinerFromDeviceIdentifier), ctx, deviceIdentifier)
}

// InvalidateMiner mocks base method.
func (m *MockCachedMinerGetter) InvalidateMiner(deviceIdentifier models.DeviceIdentifier) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateMiner", deviceIdentifier)
}

// InvalidateMiner indicates an expected call of InvalidateMiner.
func (mr *MockCachedMinerGetterMockRecorder) InvalidateMiner(deviceIdentifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateMiner", reflect.TypeOf((*MockCachedMinerGetter)(nil).InvalidateMiner), deviceIdentifier)
}
