import type { InfraDeviceItem } from "../../types";

const modbusConfig = (endpoint: string, port: number, unitId: number, registerAddress: number, writeMode: string) =>
  JSON.stringify({
    endpoint,
    port,
    unit_id: unitId,
    register_address: registerAddress,
    write_mode: writeMode,
  });

export const mockInfraDevices: InfraDeviceItem[] = [
  {
    id: "101",
    siteId: "8",
    siteName: "Austin",
    buildingName: "Building 1",
    rackName: "Rack A1",
    name: "Building 1 exhaust fans - Zone A",
    deviceKind: "fan_group",
    fanCount: 12,
    enabled: true,
    driverType: "modbus_tcp",
    driverConfig: modbusConfig("10.12.1.21", 502, 1, 2001, "holding_register"),
  },
  {
    id: "102",
    siteId: "8",
    siteName: "Austin",
    buildingName: "Building 1",
    rackName: "Rack A2",
    name: "Building 1 exhaust fans - Zone B",
    deviceKind: "fan_group",
    fanCount: 10,
    enabled: true,
    driverType: "modbus_tcp",
    driverConfig: modbusConfig("10.12.1.22", 502, 2, 2001, "holding_register"),
  },
  {
    id: "103",
    siteId: "8",
    siteName: "Austin",
    buildingName: "Building 2",
    rackName: "Rack B1",
    name: "North wall fan group",
    deviceKind: "fan_group",
    fanCount: 8,
    enabled: false,
    driverType: "modbus_tcp",
    driverConfig: modbusConfig("10.12.2.37", 44818, 1, 1, "coil"),
  },
  {
    id: "104",
    siteId: "7",
    siteName: "Denver",
    buildingName: "Building 1",
    rackName: "Rack D1",
    name: "Rack row 3 intake fan",
    deviceKind: "single_fan",
    fanCount: 1,
    enabled: true,
    driverType: "modbus_tcp",
    driverConfig: modbusConfig("10.18.1.43", 502, 3, 1, "coil"),
  },
  {
    id: "105",
    siteId: "7",
    siteName: "Denver",
    buildingName: "Building 1",
    rackName: "Rack D2",
    name: "Building 1 exhaust fans - Zone C",
    deviceKind: "fan_group",
    fanCount: 16,
    enabled: true,
    driverType: "modbus_tcp",
    driverConfig: modbusConfig("10.18.1.58", 502, 4, 2001, "holding_register"),
  },
  {
    id: "106",
    siteId: "7",
    siteName: "Denver",
    buildingName: "Building 5",
    rackName: "Rack E1",
    name: "Evaporative cooling fan bank",
    deviceKind: "fan_group",
    fanCount: 20,
    enabled: true,
    driverType: "modbus_tcp",
    driverConfig: modbusConfig("10.18.5.74", 44818, 1, 2001, "holding_register"),
  },
  {
    id: "107",
    siteId: "9",
    siteName: "Miami",
    buildingName: "Building 2",
    rackName: "Rack M1",
    name: "South aisle booster fan",
    deviceKind: "single_fan",
    fanCount: 1,
    enabled: false,
    driverType: "modbus_tcp",
    driverConfig: modbusConfig("10.24.2.16", 502, 5, 1, "coil"),
  },
  {
    id: "108",
    siteId: "9",
    siteName: "Miami",
    buildingName: "Building 10",
    rackName: "Rack M2",
    name: "Building 10 roof exhaust fans",
    deviceKind: "fan_group",
    fanCount: 14,
    enabled: true,
    driverType: "modbus_tcp",
    // Redacted driver_config, as a site:read-only caller would see it.
    driverConfig: "",
  },
];
