// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mocks/mock_message_queue.go -package=mocks MessageQueue
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	commandtype "github.com/block/proto-fleet/server/internal/domain/commandtype"
	queue "github.com/block/proto-fleet/server/internal/infrastructure/queue"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageQueue is a mock of MessageQueue interface.
type MockMessageQueue struct {
	ctrl     *gomock.Controller
	recorder *MockMessageQueueMockRecorder
	isgomock struct{}
}

// MockMessageQueueMockRecorder is the mock recorder for MockMessageQueue.
type MockMessageQueueMockRecorder struct {
	mock *MockMessageQueue
}

// NewMockMessageQueue creates a new mock instance.
func NewMockMessageQueue(ctrl *gomock.Controller) *MockMessageQueue {
	mock := &MockMessageQueue{ctrl: ctrl}
	mock.recorder = &MockMessageQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageQueue) EXPECT() *MockMessageQueueMockRecorder {
	return m.recorder
}

// Dequeue mocks base method.
func (m *MockMessageQueue) Dequeue(ctx context.Context, limit int32) ([]queue.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dequeue", ctx, limit)
	ret0, _ := ret[0].([]queue.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dequeue indicates an expected call of Dequeue.
func (mr *MockMessageQueueMockRecorder) Dequeue(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dequeue", reflect.TypeOf((*MockMessageQueue)(nil).Dequeue), ctx, limit)
}

// Enqueue mocks base method.
func (m *MockMessageQueue) Enqueue(ctx context.Context, commandBatchLogUUID string, commandType commandtype.Type, deviceIDs []int64, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, commandBatchLogUUID, commandType, deviceIDs, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockMessageQueueMockRecorder) Enqueue(ctx, commandBatchLogUUID, commandType, deviceIDs, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockMessageQueue)(nil).Enqueue), ctx, commandBatchLogUUID, commandType, deviceIDs, payload)
}

// EnqueueMany mocks base method.
func (m *MockMessageQueue) EnqueueMany(ctx context.Context, commandBatchLogUUID string, commandType commandtype.Type, messages []queue.EnqueueMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueMany", ctx, commandBatchLogUUID, commandType, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueMany indicates an expected call of EnqueueMany.
func (mr *MockMessageQueueMockRecorder) EnqueueMany(ctx, commandBatchLogUUID, commandType, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueMany", reflect.TypeOf((*MockMessageQueue)(nil).EnqueueMany), ctx, commandBatchLogUUID, commandType, messages)
}

// IsBatchFinished mocks base method.
func (m *MockMessageQueue) IsBatchFinished(ctx context.Context, commandBatchLogUUID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBatchFinished", ctx, commandBatchLogUUID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBatchFinished indicates an expected call of IsBatchFinished.
func (mr *MockMessageQueueMockRecorder) IsBatchFinished(ctx, commandBatchLogUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBatchFinished", reflect.TypeOf((*MockMessageQueue)(nil).IsBatchFinished), ctx, commandBatchLogUUID)
}

// IsBatchProcessing mocks base method.
func (m *MockMessageQueue) IsBatchProcessing(ctx context.Context, commandBatchLogUUID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBatchProcessing", ctx, commandBatchLogUUID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBatchProcessing indicates an expected call of IsBatchProcessing.
func (mr *MockMessageQueueMockRecorder) IsBatchProcessing(ctx, commandBatchLogUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBatchProcessing", reflect.TypeOf((*MockMessageQueue)(nil).IsBatchProcessing), ctx, commandBatchLogUUID)
}

// MarkFailed mocks base method.
func (m *MockMessageQueue) MarkFailed(ctx context.Context, messageID int64, errorInfo string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, messageID, errorInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockMessageQueueMockRecorder) MarkFailed(ctx, messageID, errorInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockMessageQueue)(nil).MarkFailed), ctx, messageID, errorInfo)
}

// MarkPermanentlyFailed mocks base method.
func (m *MockMessageQueue) MarkPermanentlyFailed(ctx context.Context, messageID int64, errorInfo string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPermanentlyFailed", ctx, messageID, errorInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPermanentlyFailed indicates an expected call of MarkPermanentlyFailed.
func (mr *MockMessageQueueMockRecorder) MarkPermanentlyFailed(ctx, messageID, errorInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPermanentlyFailed", reflect.TypeOf((*MockMessageQueue)(nil).MarkPermanentlyFailed), ctx, messageID, errorInfo)
}

// MarkSuccess mocks base method.
func (m *MockMessageQueue) MarkSuccess(ctx context.Context, messageID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSuccess", ctx, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSuccess indicates an expected call of MarkSuccess.
func (mr *MockMessageQueueMockRecorder) MarkSuccess(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSuccess", reflect.TypeOf((*MockMessageQueue)(nil).MarkSuccess), ctx, messageID)
}

// MaxFailureRetries mocks base method.
func (m *MockMessageQueue) MaxFailureRetries() int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxFailureRetries")
	ret0, _ := ret[0].(int32)
	return ret0
}

// MaxFailureRetries indicates an expected call of MaxFailureRetries.
func (mr *MockMessageQueueMockRecorder) MaxFailureRetries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxFailureRetries", reflect.TypeOf((*MockMessageQueue)(nil).MaxFailureRetries))
}
