// Code generated by MockGen. DO NOT EDIT.
// Source: device.go
//
// Generated by this command:
//
//	mockgen -source=device.go -destination=mocks/mock_device_store.go -package=mocks DeviceStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pairingv1 "github.com/block/proto-fleet/server/generated/grpc/pairing/v1"
	telemetryv1 "github.com/block/proto-fleet/server/generated/grpc/telemetry/v1"
	sqlc "github.com/block/proto-fleet/server/generated/sqlc"
	models "github.com/block/proto-fleet/server/internal/domain/miner/models"
	models0 "github.com/block/proto-fleet/server/internal/domain/minerdiscovery/models"
	interfaces "github.com/block/proto-fleet/server/internal/domain/stores/interfaces"
	models1 "github.com/block/proto-fleet/server/internal/domain/telemetry/models"
	secrets "github.com/block/proto-fleet/server/internal/infrastructure/secrets"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceStore is a mock of DeviceStore interface.
type MockDeviceStore struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceStoreMockRecorder
	isgomock struct{}
}

// MockDeviceStoreMockRecorder is the mock recorder for MockDeviceStore.
type MockDeviceStoreMockRecorder struct {
	mock *MockDeviceStore
}

// NewMockDeviceStore creates a new mock instance.
func NewMockDeviceStore(ctrl *gomock.Controller) *MockDeviceStore {
	mock := &MockDeviceStore{ctrl: ctrl}
	mock.recorder = &MockDeviceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceStore) EXPECT() *MockDeviceStoreMockRecorder {
	return m.recorder
}

// AllDevicesBelongToOrg mocks base method.
func (m *MockDeviceStore) AllDevicesBelongToOrg(ctx context.Context, deviceIdentifiers []string, orgID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllDevicesBelongToOrg", ctx, deviceIdentifiers, orgID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllDevicesBelongToOrg indicates an expected call of AllDevicesBelongToOrg.
func (mr *MockDeviceStoreMockRecorder) AllDevicesBelongToOrg(ctx, deviceIdentifiers, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllDevicesBelongToOrg", reflect.TypeOf((*MockDeviceStore)(nil).AllDevicesBelongToOrg), ctx, deviceIdentifiers, orgID)
}

// GetAllPairedDeviceIdentifiers mocks base method.
func (m *MockDeviceStore) GetAllPairedDeviceIdentifiers(ctx context.Context) ([]models1.DeviceIdentifier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPairedDeviceIdentifiers", ctx)
	ret0, _ := ret[0].([]models1.DeviceIdentifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPairedDeviceIdentifiers indicates an expected call of GetAllPairedDeviceIdentifiers.
func (mr *MockDeviceStoreMockRecorder) GetAllPairedDeviceIdentifiers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPairedDeviceIdentifiers", reflect.TypeOf((*MockDeviceStore)(nil).GetAllPairedDeviceIdentifiers), ctx)
}

// GetAvailableFirmwareVersions mocks base method.
func (m *MockDeviceStore) GetAvailableFirmwareVersions(ctx context.Context, orgID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableFirmwareVersions", ctx, orgID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableFirmwareVersions indicates an expected call of GetAvailableFirmwareVersions.
func (mr *MockDeviceStoreMockRecorder) GetAvailableFirmwareVersions(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableFirmwareVersions", reflect.TypeOf((*MockDeviceStore)(nil).GetAvailableFirmwareVersions), ctx, orgID)
}

// GetAvailableModels mocks base method.
func (m *MockDeviceStore) GetAvailableModels(ctx context.Context, orgID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableModels", ctx, orgID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableModels indicates an expected call of GetAvailableModels.
func (mr *MockDeviceStoreMockRecorder) GetAvailableModels(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableModels", reflect.TypeOf((*MockDeviceStore)(nil).GetAvailableModels), ctx, orgID)
}

// GetDeviceByDeviceIdentifier mocks base method.
func (m *MockDeviceStore) GetDeviceByDeviceIdentifier(ctx context.Context, identifier string, orgID int64) (*pairingv1.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByDeviceIdentifier", ctx, identifier, orgID)
	ret0, _ := ret[0].(*pairingv1.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByDeviceIdentifier indicates an expected call of GetDeviceByDeviceIdentifier.
func (mr *MockDeviceStoreMockRecorder) GetDeviceByDeviceIdentifier(ctx, identifier, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByDeviceIdentifier", reflect.TypeOf((*MockDeviceStore)(nil).GetDeviceByDeviceIdentifier), ctx, identifier, orgID)
}

// GetDeviceIdentifiersByOrgWithFilter mocks base method.
func (m *MockDeviceStore) GetDeviceIdentifiersByOrgWithFilter(ctx context.Context, orgID int64, filter *interfaces.MinerFilter) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceIdentifiersByOrgWithFilter", ctx, orgID, filter)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceIdentifiersByOrgWithFilter indicates an expected call of GetDeviceIdentifiersByOrgWithFilter.
func (mr *MockDeviceStoreMockRecorder) GetDeviceIdentifiersByOrgWithFilter(ctx, orgID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceIdentifiersByOrgWithFilter", reflect.TypeOf((*MockDeviceStore)(nil).GetDeviceIdentifiersByOrgWithFilter), ctx, orgID, filter)
}

// GetDeviceOrgDriverAndSite mocks base method.
func (m *MockDeviceStore) GetDeviceOrgDriverAndSite(ctx context.Context, deviceIdentifier models1.DeviceIdentifier) (int64, string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceOrgDriverAndSite", ctx, deviceIdentifier)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetDeviceOrgDriverAndSite indicates an expected call of GetDeviceOrgDriverAndSite.
func (mr *MockDeviceStoreMockRecorder) GetDeviceOrgDriverAndSite(ctx, deviceIdentifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceOrgDriverAndSite", reflect.TypeOf((*MockDeviceStore)(nil).GetDeviceOrgDriverAndSite), ctx, deviceIdentifier)
}

// GetDevicePropertiesForRename mocks base method.
func (m *MockDeviceStore) GetDevicePropertiesForRename(ctx context.Context, orgID int64, deviceIdentifiers []string, includeTelemetry bool) ([]interfaces.DeviceRenameProperties, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicePropertiesForRename", ctx, orgID, deviceIdentifiers, includeTelemetry)
	ret0, _ := ret[0].([]interfaces.DeviceRenameProperties)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicePropertiesForRename indicates an expected call of GetDevicePropertiesForRename.
func (mr *MockDeviceStoreMockRecorder) GetDevicePropertiesForRename(ctx, orgID, deviceIdentifiers, includeTelemetry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicePropertiesForRename", reflect.TypeOf((*MockDeviceStore)(nil).GetDevicePropertiesForRename), ctx, orgID, deviceIdentifiers, includeTelemetry)
}

// GetDeviceStatusForDeviceIdentifiers mocks base method.
func (m *MockDeviceStore) GetDeviceStatusForDeviceIdentifiers(ctx context.Context, deviceIdentifiers []models1.DeviceIdentifier) (map[models1.DeviceIdentifier]models.MinerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceStatusForDeviceIdentifiers", ctx, deviceIdentifiers)
	ret0, _ := ret[0].(map[models1.DeviceIdentifier]models.MinerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceStatusForDeviceIdentifiers indicates an expected call of GetDeviceStatusForDeviceIdentifiers.
func (mr *MockDeviceStoreMockRecorder) GetDeviceStatusForDeviceIdentifiers(ctx, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceStatusForDeviceIdentifiers", reflect.TypeOf((*MockDeviceStore)(nil).GetDeviceStatusForDeviceIdentifiers), ctx, deviceIdentifiers)
}

// GetDeviceWithIPAssignment mocks base method.
func (m *MockDeviceStore) GetDeviceWithIPAssignment(ctx context.Context, deviceIdentifier string, orgID int64) (*models0.DiscoveredDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceWithIPAssignment", ctx, deviceIdentifier, orgID)
	ret0, _ := ret[0].(*models0.DiscoveredDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceWithIPAssignment indicates an expected call of GetDeviceWithIPAssignment.
func (mr *MockDeviceStoreMockRecorder) GetDeviceWithIPAssignment(ctx, deviceIdentifier, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceWithIPAssignment", reflect.TypeOf((*MockDeviceStore)(nil).GetDeviceWithIPAssignment), ctx, deviceIdentifier, orgID)
}

// GetKnownSubnets mocks base method.
func (m *MockDeviceStore) GetKnownSubnets(ctx context.Context, orgID int64, maskBits int, isIPv4 bool) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnownSubnets", ctx, orgID, maskBits, isIPv4)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKnownSubnets indicates an expected call of GetKnownSubnets.
func (mr *MockDeviceStoreMockRecorder) GetKnownSubnets(ctx, orgID, maskBits, isIPv4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnownSubnets", reflect.TypeOf((*MockDeviceStore)(nil).GetKnownSubnets), ctx, orgID, maskBits, isIPv4)
}

// GetMinerCredentials mocks base method.
func (m *MockDeviceStore) GetMinerCredentials(ctx context.Context, device *pairingv1.Device, orgID int64) (*pairingv1.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerCredentials", ctx, device, orgID)
	ret0, _ := ret[0].(*pairingv1.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerCredentials indicates an expected call of GetMinerCredentials.
func (mr *MockDeviceStoreMockRecorder) GetMinerCredentials(ctx, device, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerCredentials", reflect.TypeOf((*MockDeviceStore)(nil).GetMinerCredentials), ctx, device, orgID)
}

// GetMinerModelGroups mocks base method.
func (m *MockDeviceStore) GetMinerModelGroups(ctx context.Context, orgID int64, filter *interfaces.MinerFilter) ([]interfaces.MinerModelGroupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerModelGroups", ctx, orgID, filter)
	ret0, _ := ret[0].([]interfaces.MinerModelGroupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerModelGroups indicates an expected call of GetMinerModelGroups.
func (mr *MockDeviceStoreMockRecorder) GetMinerModelGroups(ctx, orgID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerModelGroups", reflect.TypeOf((*MockDeviceStore)(nil).GetMinerModelGroups), ctx, orgID, filter)
}

// GetMinerStateCounts mocks base method.
func (m *MockDeviceStore) GetMinerStateCounts(ctx context.Context, orgID int64, filter *interfaces.MinerFilter) (*telemetryv1.MinerStateCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerStateCounts", ctx, orgID, filter)
	ret0, _ := ret[0].(*telemetryv1.MinerStateCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerStateCounts indicates an expected call of GetMinerStateCounts.
func (mr *MockDeviceStoreMockRecorder) GetMinerStateCounts(ctx, orgID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerStateCounts", reflect.TypeOf((*MockDeviceStore)(nil).GetMinerStateCounts), ctx, orgID, filter)
}

// GetMinerStateCountsByCollections mocks base method.
func (m *MockDeviceStore) GetMinerStateCountsByCollections(ctx context.Context, orgID int64, collectionIDs []int64) (map[int64]interfaces.MinerStateCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerStateCountsByCollections", ctx, orgID, collectionIDs)
	ret0, _ := ret[0].(map[int64]interfaces.MinerStateCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerStateCountsByCollections indicates an expected call of GetMinerStateCountsByCollections.
func (mr *MockDeviceStoreMockRecorder) GetMinerStateCountsByCollections(ctx, orgID, collectionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerStateCountsByCollections", reflect.TypeOf((*MockDeviceStore)(nil).GetMinerStateCountsByCollections), ctx, orgID, collectionIDs)
}

// GetMinerStateCountsByDeviceIDs mocks base method.
func (m *MockDeviceStore) GetMinerStateCountsByDeviceIDs(ctx context.Context, orgID int64, deviceIdentifiers []string) (interfaces.MinerStateCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerStateCountsByDeviceIDs", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].(interfaces.MinerStateCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerStateCountsByDeviceIDs indicates an expected call of GetMinerStateCountsByDeviceIDs.
func (mr *MockDeviceStoreMockRecorder) GetMinerStateCountsByDeviceIDs(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerStateCountsByDeviceIDs", reflect.TypeOf((*MockDeviceStore)(nil).GetMinerStateCountsByDeviceIDs), ctx, orgID, deviceIdentifiers)
}

// GetOfflineDevices mocks base method.
func (m *MockDeviceStore) GetOfflineDevices(ctx context.Context, limit int) ([]interfaces.OfflineDeviceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOfflineDevices", ctx, limit)
	ret0, _ := ret[0].([]interfaces.OfflineDeviceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOfflineDevices indicates an expected call of GetOfflineDevices.
func (mr *MockDeviceStoreMockRecorder) GetOfflineDevices(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOfflineDevices", reflect.TypeOf((*MockDeviceStore)(nil).GetOfflineDevices), ctx, limit)
}

// GetPairedDeviceByMACAddress mocks base method.
func (m *MockDeviceStore) GetPairedDeviceByMACAddress(ctx context.Context, macAddress string, orgID int64) (*interfaces.PairedDeviceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPairedDeviceByMACAddress", ctx, macAddress, orgID)
	ret0, _ := ret[0].(*interfaces.PairedDeviceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPairedDeviceByMACAddress indicates an expected call of GetPairedDeviceByMACAddress.
func (mr *MockDeviceStoreMockRecorder) GetPairedDeviceByMACAddress(ctx, macAddress, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPairedDeviceByMACAddress", reflect.TypeOf((*MockDeviceStore)(nil).GetPairedDeviceByMACAddress), ctx, macAddress, orgID)
}

// GetPairedDeviceBySerialNumber mocks base method.
func (m *MockDeviceStore) GetPairedDeviceBySerialNumber(ctx context.Context, serialNumber string, orgID int64) (*interfaces.PairedDeviceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPairedDeviceBySerialNumber", ctx, serialNumber, orgID)
	ret0, _ := ret[0].(*interfaces.PairedDeviceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPairedDeviceBySerialNumber indicates an expected call of GetPairedDeviceBySerialNumber.
func (mr *MockDeviceStoreMockRecorder) GetPairedDeviceBySerialNumber(ctx, serialNumber, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPairedDeviceBySerialNumber", reflect.TypeOf((*MockDeviceStore)(nil).GetPairedDeviceBySerialNumber), ctx, serialNumber, orgID)
}

// GetPairedDevicesByMACAddresses mocks base method.
func (m *MockDeviceStore) GetPairedDevicesByMACAddresses(ctx context.Context, macAddresses []string, orgID int64) (map[string]*interfaces.PairedDeviceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPairedDevicesByMACAddresses", ctx, macAddresses, orgID)
	ret0, _ := ret[0].(map[string]*interfaces.PairedDeviceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPairedDevicesByMACAddresses indicates an expected call of GetPairedDevicesByMACAddresses.
func (mr *MockDeviceStoreMockRecorder) GetPairedDevicesByMACAddresses(ctx, macAddresses, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPairedDevicesByMACAddresses", reflect.TypeOf((*MockDeviceStore)(nil).GetPairedDevicesByMACAddresses), ctx, macAddresses, orgID)
}

// GetTotalDevicesPendingAuth mocks base method.
func (m *MockDeviceStore) GetTotalDevicesPendingAuth(ctx context.Context, orgID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalDevicesPendingAuth", ctx, orgID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalDevicesPendingAuth indicates an expected call of GetTotalDevicesPendingAuth.
func (mr *MockDeviceStoreMockRecorder) GetTotalDevicesPendingAuth(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalDevicesPendingAuth", reflect.TypeOf((*MockDeviceStore)(nil).GetTotalDevicesPendingAuth), ctx, orgID)
}

// GetTotalPairedDevices mocks base method.
func (m *MockDeviceStore) GetTotalPairedDevices(ctx context.Context, orgID int64, filter *interfaces.MinerFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalPairedDevices", ctx, orgID, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalPairedDevices indicates an expected call of GetTotalPairedDevices.
func (mr *MockDeviceStoreMockRecorder) GetTotalPairedDevices(ctx, orgID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalPairedDevices", reflect.TypeOf((*MockDeviceStore)(nil).GetTotalPairedDevices), ctx, orgID, filter)
}

// InsertDevice mocks base method.
func (m *MockDeviceStore) InsertDevice(ctx context.Context, device *pairingv1.Device, orgID int64, discoveredDeviceIdentifier string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDevice", ctx, device, orgID, discoveredDeviceIdentifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertDevice indicates an expected call of InsertDevice.
func (mr *MockDeviceStoreMockRecorder) InsertDevice(ctx, device, orgID, discoveredDeviceIdentifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDevice", reflect.TypeOf((*MockDeviceStore)(nil).InsertDevice), ctx, device, orgID, discoveredDeviceIdentifier)
}

// ListMinerStateSnapshots mocks base method.
func (m *MockDeviceStore) ListMinerStateSnapshots(ctx context.Context, orgID int64, cursor string, pageSize int32, filter *interfaces.MinerFilter, sortConfig *interfaces.SortConfig) ([]sqlc.ListMinerStateSnapshotsRow, string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMinerStateSnapshots", ctx, orgID, cursor, pageSize, filter, sortConfig)
	ret0, _ := ret[0].([]sqlc.ListMinerStateSnapshotsRow)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListMinerStateSnapshots indicates an expected call of ListMinerStateSnapshots.
func (mr *MockDeviceStoreMockRecorder) ListMinerStateSnapshots(ctx, orgID, cursor, pageSize, filter, sortConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMinerStateSnapshots", reflect.TypeOf((*MockDeviceStore)(nil).ListMinerStateSnapshots), ctx, orgID, cursor, pageSize, filter, sortConfig)
}

// SetDevicePairingAuthNeededIfNotPaired mocks base method.
func (m *MockDeviceStore) SetDevicePairingAuthNeededIfNotPaired(ctx context.Context, device *pairingv1.Device, orgID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDevicePairingAuthNeededIfNotPaired", ctx, device, orgID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDevicePairingAuthNeededIfNotPaired indicates an expected call of SetDevicePairingAuthNeededIfNotPaired.
func (mr *MockDeviceStoreMockRecorder) SetDevicePairingAuthNeededIfNotPaired(ctx, device, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDevicePairingAuthNeededIfNotPaired", reflect.TypeOf((*MockDeviceStore)(nil).SetDevicePairingAuthNeededIfNotPaired), ctx, device, orgID)
}

// SoftDeleteDevices mocks base method.
func (m *MockDeviceStore) SoftDeleteDevices(ctx context.Context, deviceIdentifiers []string, orgID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteDevices", ctx, deviceIdentifiers, orgID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteDevices indicates an expected call of SoftDeleteDevices.
func (mr *MockDeviceStoreMockRecorder) SoftDeleteDevices(ctx, deviceIdentifiers, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteDevices", reflect.TypeOf((*MockDeviceStore)(nil).SoftDeleteDevices), ctx, deviceIdentifiers, orgID)
}

// UpdateDeviceCustomNames mocks base method.
func (m *MockDeviceStore) UpdateDeviceCustomNames(ctx context.Context, orgID int64, names map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceCustomNames", ctx, orgID, names)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceCustomNames indicates an expected call of UpdateDeviceCustomNames.
func (mr *MockDeviceStoreMockRecorder) UpdateDeviceCustomNames(ctx, orgID, names any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceCustomNames", reflect.TypeOf((*MockDeviceStore)(nil).UpdateDeviceCustomNames), ctx, orgID, names)
}

// UpdateDeviceInfo mocks base method.
func (m *MockDeviceStore) UpdateDeviceInfo(ctx context.Context, device *pairingv1.Device, orgID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceInfo", ctx, device, orgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceInfo indicates an expected call of UpdateDeviceInfo.
func (mr *MockDeviceStoreMockRecorder) UpdateDeviceInfo(ctx, device, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceInfo", reflect.TypeOf((*MockDeviceStore)(nil).UpdateDeviceInfo), ctx, device, orgID)
}

// UpdateDevicePairingStatusByIdentifier mocks base method.
func (m *MockDeviceStore) UpdateDevicePairingStatusByIdentifier(ctx context.Context, deviceIdentifier, pairingStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevicePairingStatusByIdentifier", ctx, deviceIdentifier, pairingStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDevicePairingStatusByIdentifier indicates an expected call of UpdateDevicePairingStatusByIdentifier.
func (mr *MockDeviceStoreMockRecorder) UpdateDevicePairingStatusByIdentifier(ctx, deviceIdentifier, pairingStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevicePairingStatusByIdentifier", reflect.TypeOf((*MockDeviceStore)(nil).UpdateDevicePairingStatusByIdentifier), ctx, deviceIdentifier, pairingStatus)
}

// UpdateFirmwareVersion mocks base method.
func (m *MockDeviceStore) UpdateFirmwareVersion(ctx context.Context, deviceIdentifier models1.DeviceIdentifier, firmwareVersion string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFirmwareVersion", ctx, deviceIdentifier, firmwareVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFirmwareVersion indicates an expected call of UpdateFirmwareVersion.
func (mr *MockDeviceStoreMockRecorder) UpdateFirmwareVersion(ctx, deviceIdentifier, firmwareVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFirmwareVersion", reflect.TypeOf((*MockDeviceStore)(nil).UpdateFirmwareVersion), ctx, deviceIdentifier, firmwareVersion)
}

// UpdateWorkerName mocks base method.
func (m *MockDeviceStore) UpdateWorkerName(ctx context.Context, deviceIdentifier models1.DeviceIdentifier, workerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkerName", ctx, deviceIdentifier, workerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkerName indicates an expected call of UpdateWorkerName.
func (mr *MockDeviceStoreMockRecorder) UpdateWorkerName(ctx, deviceIdentifier, workerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkerName", reflect.TypeOf((*MockDeviceStore)(nil).UpdateWorkerName), ctx, deviceIdentifier, workerName)
}

// UpsertDevicePairing mocks base method.
func (m *MockDeviceStore) UpsertDevicePairing(ctx context.Context, device *pairingv1.Device, orgID int64, pairingStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDevicePairing", ctx, device, orgID, pairingStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDevicePairing indicates an expected call of UpsertDevicePairing.
func (mr *MockDeviceStoreMockRecorder) UpsertDevicePairing(ctx, device, orgID, pairingStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDevicePairing", reflect.TypeOf((*MockDeviceStore)(nil).UpsertDevicePairing), ctx, device, orgID, pairingStatus)
}

// UpsertDeviceStatus mocks base method.
func (m *MockDeviceStore) UpsertDeviceStatus(ctx context.Context, deviceIdentifier models1.DeviceIdentifier, status models.MinerStatus, details string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDeviceStatus", ctx, deviceIdentifier, status, details)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDeviceStatus indicates an expected call of UpsertDeviceStatus.
func (mr *MockDeviceStoreMockRecorder) UpsertDeviceStatus(ctx, deviceIdentifier, status, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDeviceStatus", reflect.TypeOf((*MockDeviceStore)(nil).UpsertDeviceStatus), ctx, deviceIdentifier, status, details)
}

// UpsertDeviceStatuses mocks base method.
func (m *MockDeviceStore) UpsertDeviceStatuses(ctx context.Context, updates []interfaces.DeviceStatusUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDeviceStatuses", ctx, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDeviceStatuses indicates an expected call of UpsertDeviceStatuses.
func (mr *MockDeviceStoreMockRecorder) UpsertDeviceStatuses(ctx, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDeviceStatuses", reflect.TypeOf((*MockDeviceStore)(nil).UpsertDeviceStatuses), ctx, updates)
}

// UpsertMinerCredentials mocks base method.
func (m *MockDeviceStore) UpsertMinerCredentials(ctx context.Context, device *pairingv1.Device, orgID int64, usernameEnc string, passwordEnc *secrets.Text) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertMinerCredentials", ctx, device, orgID, usernameEnc, passwordEnc)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertMinerCredentials indicates an expected call of UpsertMinerCredentials.
func (mr *MockDeviceStoreMockRecorder) UpsertMinerCredentials(ctx, device, orgID, usernameEnc, passwordEnc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertMinerCredentials", reflect.TypeOf((*MockDeviceStore)(nil).UpsertMinerCredentials), ctx, device, orgID, usernameEnc, passwordEnc)
}
