// Code generated by MockGen. DO NOT EDIT.
// Source: site.go
//
// Generated by this command:
//
//	mockgen -source=site.go -destination=mocks/mock_site_store.go -package=mocks SiteStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/block/proto-fleet/server/internal/domain/sites/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSiteStore is a mock of SiteStore interface.
type MockSiteStore struct {
	ctrl     *gomock.Controller
	recorder *MockSiteStoreMockRecorder
	isgomock struct{}
}

// MockSiteStoreMockRecorder is the mock recorder for MockSiteStore.
type MockSiteStoreMockRecorder struct {
	mock *MockSiteStore
}

// NewMockSiteStore creates a new mock instance.
func NewMockSiteStore(ctrl *gomock.Controller) *MockSiteStore {
	mock := &MockSiteStore{ctrl: ctrl}
	mock.recorder = &MockSiteStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSiteStore) EXPECT() *MockSiteStoreMockRecorder {
	return m.recorder
}

// AssignBuildingToSite mocks base method.
func (m *MockSiteStore) AssignBuildingToSite(ctx context.Context, orgID, buildingID int64, targetSiteID *int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignBuildingToSite", ctx, orgID, buildingID, targetSiteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignBuildingToSite indicates an expected call of AssignBuildingToSite.
func (mr *MockSiteStoreMockRecorder) AssignBuildingToSite(ctx, orgID, buildingID, targetSiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignBuildingToSite", reflect.TypeOf((*MockSiteStore)(nil).AssignBuildingToSite), ctx, orgID, buildingID, targetSiteID)
}

// AssignBuildingsToSiteBulk mocks base method.
func (m *MockSiteStore) AssignBuildingsToSiteBulk(ctx context.Context, orgID int64, buildingIDs []int64, targetSiteID *int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignBuildingsToSiteBulk", ctx, orgID, buildingIDs, targetSiteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignBuildingsToSiteBulk indicates an expected call of AssignBuildingsToSiteBulk.
func (mr *MockSiteStoreMockRecorder) AssignBuildingsToSiteBulk(ctx, orgID, buildingIDs, targetSiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignBuildingsToSiteBulk", reflect.TypeOf((*MockSiteStore)(nil).AssignBuildingsToSiteBulk), ctx, orgID, buildingIDs, targetSiteID)
}

// AssignDevicesToSite mocks base method.
func (m *MockSiteStore) AssignDevicesToSite(ctx context.Context, orgID int64, targetSiteID *int64, deviceIdentifiers []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDevicesToSite", ctx, orgID, targetSiteID, deviceIdentifiers)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignDevicesToSite indicates an expected call of AssignDevicesToSite.
func (mr *MockSiteStoreMockRecorder) AssignDevicesToSite(ctx, orgID, targetSiteID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDevicesToSite", reflect.TypeOf((*MockSiteStore)(nil).AssignDevicesToSite), ctx, orgID, targetSiteID, deviceIdentifiers)
}

// CountBuildingsBySite mocks base method.
func (m *MockSiteStore) CountBuildingsBySite(ctx context.Context, orgID, siteID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBuildingsBySite", ctx, orgID, siteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBuildingsBySite indicates an expected call of CountBuildingsBySite.
func (mr *MockSiteStoreMockRecorder) CountBuildingsBySite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBuildingsBySite", reflect.TypeOf((*MockSiteStore)(nil).CountBuildingsBySite), ctx, orgID, siteID)
}

// CountCurtailmentResponseProfilesBySite mocks base method.
func (m *MockSiteStore) CountCurtailmentResponseProfilesBySite(ctx context.Context, orgID, siteID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCurtailmentResponseProfilesBySite", ctx, orgID, siteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCurtailmentResponseProfilesBySite indicates an expected call of CountCurtailmentResponseProfilesBySite.
func (mr *MockSiteStoreMockRecorder) CountCurtailmentResponseProfilesBySite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCurtailmentResponseProfilesBySite", reflect.TypeOf((*MockSiteStore)(nil).CountCurtailmentResponseProfilesBySite), ctx, orgID, siteID)
}

// CountInfrastructureDevicesBySite mocks base method.
func (m *MockSiteStore) CountInfrastructureDevicesBySite(ctx context.Context, orgID, siteID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountInfrastructureDevicesBySite", ctx, orgID, siteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountInfrastructureDevicesBySite indicates an expected call of CountInfrastructureDevicesBySite.
func (mr *MockSiteStoreMockRecorder) CountInfrastructureDevicesBySite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountInfrastructureDevicesBySite", reflect.TypeOf((*MockSiteStore)(nil).CountInfrastructureDevicesBySite), ctx, orgID, siteID)
}

// CountRacksBySite mocks base method.
func (m *MockSiteStore) CountRacksBySite(ctx context.Context, orgID, siteID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRacksBySite", ctx, orgID, siteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRacksBySite indicates an expected call of CountRacksBySite.
func (mr *MockSiteStoreMockRecorder) CountRacksBySite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRacksBySite", reflect.TypeOf((*MockSiteStore)(nil).CountRacksBySite), ctx, orgID, siteID)
}

// CountResponseProfilesByInfrastructureDevices mocks base method.
func (m *MockSiteStore) CountResponseProfilesByInfrastructureDevices(ctx context.Context, orgID int64, ids []int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountResponseProfilesByInfrastructureDevices", ctx, orgID, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountResponseProfilesByInfrastructureDevices indicates an expected call of CountResponseProfilesByInfrastructureDevices.
func (mr *MockSiteStoreMockRecorder) CountResponseProfilesByInfrastructureDevices(ctx, orgID, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountResponseProfilesByInfrastructureDevices", reflect.TypeOf((*MockSiteStore)(nil).CountResponseProfilesByInfrastructureDevices), ctx, orgID, ids)
}

// CreateSite mocks base method.
func (m *MockSiteStore) CreateSite(ctx context.Context, params models.CreateSiteParams) (*models.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSite", ctx, params)
	ret0, _ := ret[0].(*models.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSite indicates an expected call of CreateSite.
func (mr *MockSiteStoreMockRecorder) CreateSite(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSite", reflect.TypeOf((*MockSiteStore)(nil).CreateSite), ctx, params)
}

// DeleteCurtailmentResponseProfilesBySite mocks base method.
func (m *MockSiteStore) DeleteCurtailmentResponseProfilesBySite(ctx context.Context, orgID, siteID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCurtailmentResponseProfilesBySite", ctx, orgID, siteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCurtailmentResponseProfilesBySite indicates an expected call of DeleteCurtailmentResponseProfilesBySite.
func (mr *MockSiteStoreMockRecorder) DeleteCurtailmentResponseProfilesBySite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCurtailmentResponseProfilesBySite", reflect.TypeOf((*MockSiteStore)(nil).DeleteCurtailmentResponseProfilesBySite), ctx, orgID, siteID)
}

// FindDeviceSiteConflicts mocks base method.
func (m *MockSiteStore) FindDeviceSiteConflicts(ctx context.Context, orgID int64, deviceIdentifiers []string) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDeviceSiteConflicts", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDeviceSiteConflicts indicates an expected call of FindDeviceSiteConflicts.
func (mr *MockSiteStoreMockRecorder) FindDeviceSiteConflicts(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDeviceSiteConflicts", reflect.TypeOf((*MockSiteStore)(nil).FindDeviceSiteConflicts), ctx, orgID, deviceIdentifiers)
}

// FindDevicesInSiteLessRacks mocks base method.
func (m *MockSiteStore) FindDevicesInSiteLessRacks(ctx context.Context, orgID int64, deviceIdentifiers []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDevicesInSiteLessRacks", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDevicesInSiteLessRacks indicates an expected call of FindDevicesInSiteLessRacks.
func (mr *MockSiteStoreMockRecorder) FindDevicesInSiteLessRacks(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDevicesInSiteLessRacks", reflect.TypeOf((*MockSiteStore)(nil).FindDevicesInSiteLessRacks), ctx, orgID, deviceIdentifiers)
}

// GetDistinctDeviceSiteIDs mocks base method.
func (m *MockSiteStore) GetDistinctDeviceSiteIDs(ctx context.Context, orgID int64, deviceIdentifiers []string) ([]*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctDeviceSiteIDs", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].([]*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctDeviceSiteIDs indicates an expected call of GetDistinctDeviceSiteIDs.
func (mr *MockSiteStoreMockRecorder) GetDistinctDeviceSiteIDs(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctDeviceSiteIDs", reflect.TypeOf((*MockSiteStore)(nil).GetDistinctDeviceSiteIDs), ctx, orgID, deviceIdentifiers)
}

// GetInfrastructureControlSubnets mocks base method.
func (m *MockSiteStore) GetInfrastructureControlSubnets(ctx context.Context, orgID, siteID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfrastructureControlSubnets", ctx, orgID, siteID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfrastructureControlSubnets indicates an expected call of GetInfrastructureControlSubnets.
func (mr *MockSiteStoreMockRecorder) GetInfrastructureControlSubnets(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfrastructureControlSubnets", reflect.TypeOf((*MockSiteStore)(nil).GetInfrastructureControlSubnets), ctx, orgID, siteID)
}

// GetSite mocks base method.
func (m *MockSiteStore) GetSite(ctx context.Context, orgID, id int64) (*models.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSite", ctx, orgID, id)
	ret0, _ := ret[0].(*models.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSite indicates an expected call of GetSite.
func (mr *MockSiteStoreMockRecorder) GetSite(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSite", reflect.TypeOf((*MockSiteStore)(nil).GetSite), ctx, orgID, id)
}

// GetSiteBySlug mocks base method.
func (m *MockSiteStore) GetSiteBySlug(ctx context.Context, orgID int64, slug string) (*models.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSiteBySlug", ctx, orgID, slug)
	ret0, _ := ret[0].(*models.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSiteBySlug indicates an expected call of GetSiteBySlug.
func (mr *MockSiteStoreMockRecorder) GetSiteBySlug(ctx, orgID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiteBySlug", reflect.TypeOf((*MockSiteStore)(nil).GetSiteBySlug), ctx, orgID, slug)
}

// ListAllSiteNetworkConfigs mocks base method.
func (m *MockSiteStore) ListAllSiteNetworkConfigs(ctx context.Context, orgID, excludeID int64) ([]models.SiteNetworkConfigEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllSiteNetworkConfigs", ctx, orgID, excludeID)
	ret0, _ := ret[0].([]models.SiteNetworkConfigEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllSiteNetworkConfigs indicates an expected call of ListAllSiteNetworkConfigs.
func (mr *MockSiteStoreMockRecorder) ListAllSiteNetworkConfigs(ctx, orgID, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllSiteNetworkConfigs", reflect.TypeOf((*MockSiteStore)(nil).ListAllSiteNetworkConfigs), ctx, orgID, excludeID)
}

// ListExistingDeviceIdentifiers mocks base method.
func (m *MockSiteStore) ListExistingDeviceIdentifiers(ctx context.Context, orgID int64, deviceIdentifiers []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExistingDeviceIdentifiers", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExistingDeviceIdentifiers indicates an expected call of ListExistingDeviceIdentifiers.
func (mr *MockSiteStoreMockRecorder) ListExistingDeviceIdentifiers(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExistingDeviceIdentifiers", reflect.TypeOf((*MockSiteStore)(nil).ListExistingDeviceIdentifiers), ctx, orgID, deviceIdentifiers)
}

// ListSiteSlugs mocks base method.
func (m *MockSiteStore) ListSiteSlugs(ctx context.Context, orgID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSiteSlugs", ctx, orgID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSiteSlugs indicates an expected call of ListSiteSlugs.
func (mr *MockSiteStoreMockRecorder) ListSiteSlugs(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSiteSlugs", reflect.TypeOf((*MockSiteStore)(nil).ListSiteSlugs), ctx, orgID)
}

// ListSites mocks base method.
func (m *MockSiteStore) ListSites(ctx context.Context, orgID int64) ([]models.SiteWithCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSites", ctx, orgID)
	ret0, _ := ret[0].([]models.SiteWithCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSites indicates an expected call of ListSites.
func (mr *MockSiteStoreMockRecorder) ListSites(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSites", reflect.TypeOf((*MockSiteStore)(nil).ListSites), ctx, orgID)
}

// LockBuildingForWrite mocks base method.
func (m *MockSiteStore) LockBuildingForWrite(ctx context.Context, orgID, buildingID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockBuildingForWrite", ctx, orgID, buildingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockBuildingForWrite indicates an expected call of LockBuildingForWrite.
func (mr *MockSiteStoreMockRecorder) LockBuildingForWrite(ctx, orgID, buildingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockBuildingForWrite", reflect.TypeOf((*MockSiteStore)(nil).LockBuildingForWrite), ctx, orgID, buildingID)
}

// LockBuildingsBySiteForWrite mocks base method.
func (m *MockSiteStore) LockBuildingsBySiteForWrite(ctx context.Context, orgID, siteID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockBuildingsBySiteForWrite", ctx, orgID, siteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockBuildingsBySiteForWrite indicates an expected call of LockBuildingsBySiteForWrite.
func (mr *MockSiteStoreMockRecorder) LockBuildingsBySiteForWrite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockBuildingsBySiteForWrite", reflect.TypeOf((*MockSiteStore)(nil).LockBuildingsBySiteForWrite), ctx, orgID, siteID)
}

// LockDevicesForReassign mocks base method.
func (m *MockSiteStore) LockDevicesForReassign(ctx context.Context, orgID int64, deviceIdentifiers []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockDevicesForReassign", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockDevicesForReassign indicates an expected call of LockDevicesForReassign.
func (mr *MockSiteStoreMockRecorder) LockDevicesForReassign(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockDevicesForReassign", reflect.TypeOf((*MockSiteStore)(nil).LockDevicesForReassign), ctx, orgID, deviceIdentifiers)
}

// LockInfrastructureDevicesBySiteForWrite mocks base method.
func (m *MockSiteStore) LockInfrastructureDevicesBySiteForWrite(ctx context.Context, orgID, siteID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockInfrastructureDevicesBySiteForWrite", ctx, orgID, siteID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockInfrastructureDevicesBySiteForWrite indicates an expected call of LockInfrastructureDevicesBySiteForWrite.
func (mr *MockSiteStoreMockRecorder) LockInfrastructureDevicesBySiteForWrite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockInfrastructureDevicesBySiteForWrite", reflect.TypeOf((*MockSiteStore)(nil).LockInfrastructureDevicesBySiteForWrite), ctx, orgID, siteID)
}

// LockSiteForWrite mocks base method.
func (m *MockSiteStore) LockSiteForWrite(ctx context.Context, orgID, siteID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSiteForWrite", ctx, orgID, siteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockSiteForWrite indicates an expected call of LockSiteForWrite.
func (mr *MockSiteStoreMockRecorder) LockSiteForWrite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSiteForWrite", reflect.TypeOf((*MockSiteStore)(nil).LockSiteForWrite), ctx, orgID, siteID)
}

// ReassignDevicesUnderBuilding mocks base method.
func (m *MockSiteStore) ReassignDevicesUnderBuilding(ctx context.Context, orgID, buildingID int64, targetSiteID *int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignDevicesUnderBuilding", ctx, orgID, buildingID, targetSiteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReassignDevicesUnderBuilding indicates an expected call of ReassignDevicesUnderBuilding.
func (mr *MockSiteStoreMockRecorder) ReassignDevicesUnderBuilding(ctx, orgID, buildingID, targetSiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignDevicesUnderBuilding", reflect.TypeOf((*MockSiteStore)(nil).ReassignDevicesUnderBuilding), ctx, orgID, buildingID, targetSiteID)
}

// ReassignDevicesUnderBuildingsBulk mocks base method.
func (m *MockSiteStore) ReassignDevicesUnderBuildingsBulk(ctx context.Context, orgID int64, buildingIDs []int64, targetSiteID *int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignDevicesUnderBuildingsBulk", ctx, orgID, buildingIDs, targetSiteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReassignDevicesUnderBuildingsBulk indicates an expected call of ReassignDevicesUnderBuildingsBulk.
func (mr *MockSiteStoreMockRecorder) ReassignDevicesUnderBuildingsBulk(ctx, orgID, buildingIDs, targetSiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignDevicesUnderBuildingsBulk", reflect.TypeOf((*MockSiteStore)(nil).ReassignDevicesUnderBuildingsBulk), ctx, orgID, buildingIDs, targetSiteID)
}

// ReassignRacksUnderBuilding mocks base method.
func (m *MockSiteStore) ReassignRacksUnderBuilding(ctx context.Context, orgID, buildingID int64, targetSiteID *int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignRacksUnderBuilding", ctx, orgID, buildingID, targetSiteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReassignRacksUnderBuilding indicates an expected call of ReassignRacksUnderBuilding.
func (mr *MockSiteStoreMockRecorder) ReassignRacksUnderBuilding(ctx, orgID, buildingID, targetSiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignRacksUnderBuilding", reflect.TypeOf((*MockSiteStore)(nil).ReassignRacksUnderBuilding), ctx, orgID, buildingID, targetSiteID)
}

// ReassignRacksUnderBuildingsBulk mocks base method.
func (m *MockSiteStore) ReassignRacksUnderBuildingsBulk(ctx context.Context, orgID int64, buildingIDs []int64, targetSiteID *int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignRacksUnderBuildingsBulk", ctx, orgID, buildingIDs, targetSiteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReassignRacksUnderBuildingsBulk indicates an expected call of ReassignRacksUnderBuildingsBulk.
func (mr *MockSiteStoreMockRecorder) ReassignRacksUnderBuildingsBulk(ctx, orgID, buildingIDs, targetSiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignRacksUnderBuildingsBulk", reflect.TypeOf((*MockSiteStore)(nil).ReassignRacksUnderBuildingsBulk), ctx, orgID, buildingIDs, targetSiteID)
}

// SetInfrastructureControlSubnets mocks base method.
func (m *MockSiteStore) SetInfrastructureControlSubnets(ctx context.Context, orgID, siteID int64, canonical string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInfrastructureControlSubnets", ctx, orgID, siteID, canonical)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetInfrastructureControlSubnets indicates an expected call of SetInfrastructureControlSubnets.
func (mr *MockSiteStoreMockRecorder) SetInfrastructureControlSubnets(ctx, orgID, siteID, canonical any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInfrastructureControlSubnets", reflect.TypeOf((*MockSiteStore)(nil).SetInfrastructureControlSubnets), ctx, orgID, siteID, canonical)
}

// SiteBelongsToOrg mocks base method.
func (m *MockSiteStore) SiteBelongsToOrg(ctx context.Context, orgID, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SiteBelongsToOrg", ctx, orgID, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SiteBelongsToOrg indicates an expected call of SiteBelongsToOrg.
func (mr *MockSiteStoreMockRecorder) SiteBelongsToOrg(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SiteBelongsToOrg", reflect.TypeOf((*MockSiteStore)(nil).SiteBelongsToOrg), ctx, orgID, id)
}

// SitesByIDs mocks base method.
func (m *MockSiteStore) SitesByIDs(ctx context.Context, orgID int64, ids []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SitesByIDs", ctx, orgID, ids)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SitesByIDs indicates an expected call of SitesByIDs.
func (mr *MockSiteStoreMockRecorder) SitesByIDs(ctx, orgID, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SitesByIDs", reflect.TypeOf((*MockSiteStore)(nil).SitesByIDs), ctx, orgID, ids)
}

// SoftDeleteBuildingsBySite mocks base method.
func (m *MockSiteStore) SoftDeleteBuildingsBySite(ctx context.Context, orgID, siteID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteBuildingsBySite", ctx, orgID, siteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteBuildingsBySite indicates an expected call of SoftDeleteBuildingsBySite.
func (mr *MockSiteStoreMockRecorder) SoftDeleteBuildingsBySite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteBuildingsBySite", reflect.TypeOf((*MockSiteStore)(nil).SoftDeleteBuildingsBySite), ctx, orgID, siteID)
}

// SoftDeleteInfrastructureDevicesBySite mocks base method.
func (m *MockSiteStore) SoftDeleteInfrastructureDevicesBySite(ctx context.Context, orgID, siteID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteInfrastructureDevicesBySite", ctx, orgID, siteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteInfrastructureDevicesBySite indicates an expected call of SoftDeleteInfrastructureDevicesBySite.
func (mr *MockSiteStoreMockRecorder) SoftDeleteInfrastructureDevicesBySite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteInfrastructureDevicesBySite", reflect.TypeOf((*MockSiteStore)(nil).SoftDeleteInfrastructureDevicesBySite), ctx, orgID, siteID)
}

// SoftDeleteSite mocks base method.
func (m *MockSiteStore) SoftDeleteSite(ctx context.Context, orgID, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteSite", ctx, orgID, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteSite indicates an expected call of SoftDeleteSite.
func (mr *MockSiteStoreMockRecorder) SoftDeleteSite(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteSite", reflect.TypeOf((*MockSiteStore)(nil).SoftDeleteSite), ctx, orgID, id)
}

// UnassignDevicesFromSite mocks base method.
func (m *MockSiteStore) UnassignDevicesFromSite(ctx context.Context, orgID, siteID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignDevicesFromSite", ctx, orgID, siteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignDevicesFromSite indicates an expected call of UnassignDevicesFromSite.
func (mr *MockSiteStoreMockRecorder) UnassignDevicesFromSite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignDevicesFromSite", reflect.TypeOf((*MockSiteStore)(nil).UnassignDevicesFromSite), ctx, orgID, siteID)
}

// UnassignRacksFromBuildingsBySite mocks base method.
func (m *MockSiteStore) UnassignRacksFromBuildingsBySite(ctx context.Context, orgID, siteID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignRacksFromBuildingsBySite", ctx, orgID, siteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignRacksFromBuildingsBySite indicates an expected call of UnassignRacksFromBuildingsBySite.
func (mr *MockSiteStoreMockRecorder) UnassignRacksFromBuildingsBySite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignRacksFromBuildingsBySite", reflect.TypeOf((*MockSiteStore)(nil).UnassignRacksFromBuildingsBySite), ctx, orgID, siteID)
}

// UnassignRacksFromSite mocks base method.
func (m *MockSiteStore) UnassignRacksFromSite(ctx context.Context, orgID, siteID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignRacksFromSite", ctx, orgID, siteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignRacksFromSite indicates an expected call of UnassignRacksFromSite.
func (mr *MockSiteStoreMockRecorder) UnassignRacksFromSite(ctx, orgID, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignRacksFromSite", reflect.TypeOf((*MockSiteStore)(nil).UnassignRacksFromSite), ctx, orgID, siteID)
}

// UpdateSite mocks base method.
func (m *MockSiteStore) UpdateSite(ctx context.Context, params models.UpdateSiteParams) (*models.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSite", ctx, params)
	ret0, _ := ret[0].(*models.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSite indicates an expected call of UpdateSite.
func (mr *MockSiteStoreMockRecorder) UpdateSite(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSite", reflect.TypeOf((*MockSiteStore)(nil).UpdateSite), ctx, params)
}
