// Code generated by MockGen. DO NOT EDIT.
// Source: collection.go
//
// Generated by this command:
//
//	mockgen -source=collection.go -destination=mocks/mock_collection_store.go -package=mocks CollectionStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	collectionv1 "github.com/block/proto-fleet/server/generated/grpc/collection/v1"
	interfaces "github.com/block/proto-fleet/server/internal/domain/stores/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockCollectionStore is a mock of CollectionStore interface.
type MockCollectionStore struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionStoreMockRecorder
	isgomock struct{}
}

// MockCollectionStoreMockRecorder is the mock recorder for MockCollectionStore.
type MockCollectionStoreMockRecorder struct {
	mock *MockCollectionStore
}

// NewMockCollectionStore creates a new mock instance.
func NewMockCollectionStore(ctrl *gomock.Controller) *MockCollectionStore {
	mock := &MockCollectionStore{ctrl: ctrl}
	mock.recorder = &MockCollectionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionStore) EXPECT() *MockCollectionStoreMockRecorder {
	return m.recorder
}

// AddDevicesToCollection mocks base method.
func (m *MockCollectionStore) AddDevicesToCollection(ctx context.Context, orgID, collectionID int64, deviceIdentifiers []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDevicesToCollection", ctx, orgID, collectionID, deviceIdentifiers)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDevicesToCollection indicates an expected call of AddDevicesToCollection.
func (mr *MockCollectionStoreMockRecorder) AddDevicesToCollection(ctx, orgID, collectionID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDevicesToCollection", reflect.TypeOf((*MockCollectionStore)(nil).AddDevicesToCollection), ctx, orgID, collectionID, deviceIdentifiers)
}

// CascadeAddedDeviceSites mocks base method.
func (m *MockCollectionStore) CascadeAddedDeviceSites(ctx context.Context, orgID, deviceSetID int64, deviceIdentifiers []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CascadeAddedDeviceSites", ctx, orgID, deviceSetID, deviceIdentifiers)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CascadeAddedDeviceSites indicates an expected call of CascadeAddedDeviceSites.
func (mr *MockCollectionStoreMockRecorder) CascadeAddedDeviceSites(ctx, orgID, deviceSetID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CascadeAddedDeviceSites", reflect.TypeOf((*MockCollectionStore)(nil).CascadeAddedDeviceSites), ctx, orgID, deviceSetID, deviceIdentifiers)
}

// CascadeRackDeviceSites mocks base method.
func (m *MockCollectionStore) CascadeRackDeviceSites(ctx context.Context, collectionID, orgID int64, targetSiteID *int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CascadeRackDeviceSites", ctx, collectionID, orgID, targetSiteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CascadeRackDeviceSites indicates an expected call of CascadeRackDeviceSites.
func (mr *MockCollectionStoreMockRecorder) CascadeRackDeviceSites(ctx, collectionID, orgID, targetSiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CascadeRackDeviceSites", reflect.TypeOf((*MockCollectionStore)(nil).CascadeRackDeviceSites), ctx, collectionID, orgID, targetSiteID)
}

// ClearRackSlotPosition mocks base method.
func (m *MockCollectionStore) ClearRackSlotPosition(ctx context.Context, collectionID int64, deviceIdentifier string, orgID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearRackSlotPosition", ctx, collectionID, deviceIdentifier, orgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearRackSlotPosition indicates an expected call of ClearRackSlotPosition.
func (mr *MockCollectionStoreMockRecorder) ClearRackSlotPosition(ctx, collectionID, deviceIdentifier, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearRackSlotPosition", reflect.TypeOf((*MockCollectionStore)(nil).ClearRackSlotPosition), ctx, collectionID, deviceIdentifier, orgID)
}

// CollectionBelongsToOrg mocks base method.
func (m *MockCollectionStore) CollectionBelongsToOrg(ctx context.Context, collectionID, orgID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectionBelongsToOrg", ctx, collectionID, orgID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectionBelongsToOrg indicates an expected call of CollectionBelongsToOrg.
func (mr *MockCollectionStoreMockRecorder) CollectionBelongsToOrg(ctx, collectionID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectionBelongsToOrg", reflect.TypeOf((*MockCollectionStore)(nil).CollectionBelongsToOrg), ctx, collectionID, orgID)
}

// CreateCollection mocks base method.
func (m *MockCollectionStore) CreateCollection(ctx context.Context, orgID int64, collectionType collectionv1.CollectionType, label, description string) (*collectionv1.DeviceCollection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCollection", ctx, orgID, collectionType, label, description)
	ret0, _ := ret[0].(*collectionv1.DeviceCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCollection indicates an expected call of CreateCollection.
func (mr *MockCollectionStoreMockRecorder) CreateCollection(ctx, orgID, collectionType, label, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCollection", reflect.TypeOf((*MockCollectionStore)(nil).CreateCollection), ctx, orgID, collectionType, label, description)
}

// CreateRackExtension mocks base method.
func (m *MockCollectionStore) CreateRackExtension(ctx context.Context, params interfaces.CreateRackExtensionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRackExtension", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRackExtension indicates an expected call of CreateRackExtension.
func (mr *MockCollectionStoreMockRecorder) CreateRackExtension(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRackExtension", reflect.TypeOf((*MockCollectionStore)(nil).CreateRackExtension), ctx, params)
}

// GetAddedDeviceSiteConflicts mocks base method.
func (m *MockCollectionStore) GetAddedDeviceSiteConflicts(ctx context.Context, orgID, deviceSetID int64, deviceIdentifiers []string) ([]interfaces.AddedDeviceSiteConflict, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddedDeviceSiteConflicts", ctx, orgID, deviceSetID, deviceIdentifiers)
	ret0, _ := ret[0].([]interfaces.AddedDeviceSiteConflict)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddedDeviceSiteConflicts indicates an expected call of GetAddedDeviceSiteConflicts.
func (mr *MockCollectionStoreMockRecorder) GetAddedDeviceSiteConflicts(ctx, orgID, deviceSetID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddedDeviceSiteConflicts", reflect.TypeOf((*MockCollectionStore)(nil).GetAddedDeviceSiteConflicts), ctx, orgID, deviceSetID, deviceIdentifiers)
}

// GetBuildingSite mocks base method.
func (m *MockCollectionStore) GetBuildingSite(ctx context.Context, orgID, buildingID int64) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildingSite", ctx, orgID, buildingID)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildingSite indicates an expected call of GetBuildingSite.
func (mr *MockCollectionStoreMockRecorder) GetBuildingSite(ctx, orgID, buildingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildingSite", reflect.TypeOf((*MockCollectionStore)(nil).GetBuildingSite), ctx, orgID, buildingID)
}

// GetCollection mocks base method.
func (m *MockCollectionStore) GetCollection(ctx context.Context, orgID, collectionID int64) (*collectionv1.DeviceCollection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollection", ctx, orgID, collectionID)
	ret0, _ := ret[0].(*collectionv1.DeviceCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockCollectionStoreMockRecorder) GetCollection(ctx, orgID, collectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockCollectionStore)(nil).GetCollection), ctx, orgID, collectionID)
}

// GetCollectionType mocks base method.
func (m *MockCollectionStore) GetCollectionType(ctx context.Context, orgID, collectionID int64) (collectionv1.CollectionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectionType", ctx, orgID, collectionID)
	ret0, _ := ret[0].(collectionv1.CollectionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectionType indicates an expected call of GetCollectionType.
func (mr *MockCollectionStoreMockRecorder) GetCollectionType(ctx, orgID, collectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectionType", reflect.TypeOf((*MockCollectionStore)(nil).GetCollectionType), ctx, orgID, collectionID)
}

// GetCollectionTypes mocks base method.
func (m *MockCollectionStore) GetCollectionTypes(ctx context.Context, orgID int64, collectionIDs []int64) (map[int64]collectionv1.CollectionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectionTypes", ctx, orgID, collectionIDs)
	ret0, _ := ret[0].(map[int64]collectionv1.CollectionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectionTypes indicates an expected call of GetCollectionTypes.
func (mr *MockCollectionStoreMockRecorder) GetCollectionTypes(ctx, orgID, collectionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectionTypes", reflect.TypeOf((*MockCollectionStore)(nil).GetCollectionTypes), ctx, orgID, collectionIDs)
}

// GetDeviceCollections mocks base method.
func (m *MockCollectionStore) GetDeviceCollections(ctx context.Context, orgID int64, deviceIdentifier string, collectionType collectionv1.CollectionType) ([]*collectionv1.DeviceCollection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCollections", ctx, orgID, deviceIdentifier, collectionType)
	ret0, _ := ret[0].([]*collectionv1.DeviceCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceCollections indicates an expected call of GetDeviceCollections.
func (mr *MockCollectionStoreMockRecorder) GetDeviceCollections(ctx, orgID, deviceIdentifier, collectionType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCollections", reflect.TypeOf((*MockCollectionStore)(nil).GetDeviceCollections), ctx, orgID, deviceIdentifier, collectionType)
}

// GetDeviceIdentifiersByDeviceSetID mocks base method.
func (m *MockCollectionStore) GetDeviceIdentifiersByDeviceSetID(ctx context.Context, deviceSetID, orgID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceIdentifiersByDeviceSetID", ctx, deviceSetID, orgID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceIdentifiersByDeviceSetID indicates an expected call of GetDeviceIdentifiersByDeviceSetID.
func (mr *MockCollectionStoreMockRecorder) GetDeviceIdentifiersByDeviceSetID(ctx, deviceSetID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceIdentifiersByDeviceSetID", reflect.TypeOf((*MockCollectionStore)(nil).GetDeviceIdentifiersByDeviceSetID), ctx, deviceSetID, orgID)
}

// GetDeviceSiteIDsByMembership mocks base method.
func (m *MockCollectionStore) GetDeviceSiteIDsByMembership(ctx context.Context, collectionID, orgID int64) (map[string]*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceSiteIDsByMembership", ctx, collectionID, orgID)
	ret0, _ := ret[0].(map[string]*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceSiteIDsByMembership indicates an expected call of GetDeviceSiteIDsByMembership.
func (mr *MockCollectionStoreMockRecorder) GetDeviceSiteIDsByMembership(ctx, collectionID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceSiteIDsByMembership", reflect.TypeOf((*MockCollectionStore)(nil).GetDeviceSiteIDsByMembership), ctx, collectionID, orgID)
}

// GetGroupLabelsForDevices mocks base method.
func (m *MockCollectionStore) GetGroupLabelsForDevices(ctx context.Context, orgID int64, deviceIdentifiers []string) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupLabelsForDevices", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupLabelsForDevices indicates an expected call of GetGroupLabelsForDevices.
func (mr *MockCollectionStoreMockRecorder) GetGroupLabelsForDevices(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupLabelsForDevices", reflect.TypeOf((*MockCollectionStore)(nil).GetGroupLabelsForDevices), ctx, orgID, deviceIdentifiers)
}

// GetRackDetailsForDevices mocks base method.
func (m *MockCollectionStore) GetRackDetailsForDevices(ctx context.Context, orgID int64, deviceIdentifiers []string) (map[string]interfaces.DeviceRackDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRackDetailsForDevices", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].(map[string]interfaces.DeviceRackDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRackDetailsForDevices indicates an expected call of GetRackDetailsForDevices.
func (mr *MockCollectionStoreMockRecorder) GetRackDetailsForDevices(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRackDetailsForDevices", reflect.TypeOf((*MockCollectionStore)(nil).GetRackDetailsForDevices), ctx, orgID, deviceIdentifiers)
}

// GetRackInfo mocks base method.
func (m *MockCollectionStore) GetRackInfo(ctx context.Context, collectionID, orgID int64) (*collectionv1.RackInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRackInfo", ctx, collectionID, orgID)
	ret0, _ := ret[0].(*collectionv1.RackInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRackInfo indicates an expected call of GetRackInfo.
func (mr *MockCollectionStoreMockRecorder) GetRackInfo(ctx, collectionID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRackInfo", reflect.TypeOf((*MockCollectionStore)(nil).GetRackInfo), ctx, collectionID, orgID)
}

// GetRackSlotStatuses mocks base method.
func (m *MockCollectionStore) GetRackSlotStatuses(ctx context.Context, orgID int64, collectionIDs []int64) (map[int64][]*collectionv1.RackSlotStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRackSlotStatuses", ctx, orgID, collectionIDs)
	ret0, _ := ret[0].(map[int64][]*collectionv1.RackSlotStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRackSlotStatuses indicates an expected call of GetRackSlotStatuses.
func (mr *MockCollectionStoreMockRecorder) GetRackSlotStatuses(ctx, orgID, collectionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRackSlotStatuses", reflect.TypeOf((*MockCollectionStore)(nil).GetRackSlotStatuses), ctx, orgID, collectionIDs)
}

// GetRackSlots mocks base method.
func (m *MockCollectionStore) GetRackSlots(ctx context.Context, collectionID, orgID int64) ([]*collectionv1.RackSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRackSlots", ctx, collectionID, orgID)
	ret0, _ := ret[0].([]*collectionv1.RackSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRackSlots indicates an expected call of GetRackSlots.
func (mr *MockCollectionStoreMockRecorder) GetRackSlots(ctx, collectionID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRackSlots", reflect.TypeOf((*MockCollectionStore)(nil).GetRackSlots), ctx, collectionID, orgID)
}

// ListCollectionMembers mocks base method.
func (m *MockCollectionStore) ListCollectionMembers(ctx context.Context, orgID, collectionID int64, pageSize int32, pageToken string) ([]*collectionv1.CollectionMember, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollectionMembers", ctx, orgID, collectionID, pageSize, pageToken)
	ret0, _ := ret[0].([]*collectionv1.CollectionMember)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCollectionMembers indicates an expected call of ListCollectionMembers.
func (mr *MockCollectionStoreMockRecorder) ListCollectionMembers(ctx, orgID, collectionID, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollectionMembers", reflect.TypeOf((*MockCollectionStore)(nil).ListCollectionMembers), ctx, orgID, collectionID, pageSize, pageToken)
}

// ListCollections mocks base method.
func (m *MockCollectionStore) ListCollections(ctx context.Context, orgID int64, collectionType collectionv1.CollectionType, pageSize int32, pageToken string, sort *interfaces.SortConfig, errorComponentTypes []int32, zones []string) ([]*collectionv1.DeviceCollection, string, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollections", ctx, orgID, collectionType, pageSize, pageToken, sort, errorComponentTypes, zones)
	ret0, _ := ret[0].([]*collectionv1.DeviceCollection)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(int32)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListCollections indicates an expected call of ListCollections.
func (mr *MockCollectionStoreMockRecorder) ListCollections(ctx, orgID, collectionType, pageSize, pageToken, sort, errorComponentTypes, zones any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollections", reflect.TypeOf((*MockCollectionStore)(nil).ListCollections), ctx, orgID, collectionType, pageSize, pageToken, sort, errorComponentTypes, zones)
}

// ListRackTypes mocks base method.
func (m *MockCollectionStore) ListRackTypes(ctx context.Context, orgID int64) ([]*collectionv1.RackType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRackTypes", ctx, orgID)
	ret0, _ := ret[0].([]*collectionv1.RackType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRackTypes indicates an expected call of ListRackTypes.
func (mr *MockCollectionStoreMockRecorder) ListRackTypes(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRackTypes", reflect.TypeOf((*MockCollectionStore)(nil).ListRackTypes), ctx, orgID)
}

// ListRackZones mocks base method.
func (m *MockCollectionStore) ListRackZones(ctx context.Context, orgID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRackZones", ctx, orgID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRackZones indicates an expected call of ListRackZones.
func (mr *MockCollectionStoreMockRecorder) ListRackZones(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRackZones", reflect.TypeOf((*MockCollectionStore)(nil).ListRackZones), ctx, orgID)
}

// LockRackPlacementForWrite mocks base method.
func (m *MockCollectionStore) LockRackPlacementForWrite(ctx context.Context, collectionID, orgID int64) (interfaces.RackPlacement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockRackPlacementForWrite", ctx, collectionID, orgID)
	ret0, _ := ret[0].(interfaces.RackPlacement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockRackPlacementForWrite indicates an expected call of LockRackPlacementForWrite.
func (mr *MockCollectionStoreMockRecorder) LockRackPlacementForWrite(ctx, collectionID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockRackPlacementForWrite", reflect.TypeOf((*MockCollectionStore)(nil).LockRackPlacementForWrite), ctx, collectionID, orgID)
}

// RemoveAllDevicesFromCollection mocks base method.
func (m *MockCollectionStore) RemoveAllDevicesFromCollection(ctx context.Context, orgID, collectionID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllDevicesFromCollection", ctx, orgID, collectionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveAllDevicesFromCollection indicates an expected call of RemoveAllDevicesFromCollection.
func (mr *MockCollectionStoreMockRecorder) RemoveAllDevicesFromCollection(ctx, orgID, collectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllDevicesFromCollection", reflect.TypeOf((*MockCollectionStore)(nil).RemoveAllDevicesFromCollection), ctx, orgID, collectionID)
}

// RemoveDevicesFromCollection mocks base method.
func (m *MockCollectionStore) RemoveDevicesFromCollection(ctx context.Context, orgID, collectionID int64, deviceIdentifiers []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDevicesFromCollection", ctx, orgID, collectionID, deviceIdentifiers)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveDevicesFromCollection indicates an expected call of RemoveDevicesFromCollection.
func (mr *MockCollectionStoreMockRecorder) RemoveDevicesFromCollection(ctx, orgID, collectionID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDevicesFromCollection", reflect.TypeOf((*MockCollectionStore)(nil).RemoveDevicesFromCollection), ctx, orgID, collectionID, deviceIdentifiers)
}

// SetRackSlotPosition mocks base method.
func (m *MockCollectionStore) SetRackSlotPosition(ctx context.Context, collectionID int64, deviceIdentifier string, row, column int32, orgID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRackSlotPosition", ctx, collectionID, deviceIdentifier, row, column, orgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRackSlotPosition indicates an expected call of SetRackSlotPosition.
func (mr *MockCollectionStoreMockRecorder) SetRackSlotPosition(ctx, collectionID, deviceIdentifier, row, column, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRackSlotPosition", reflect.TypeOf((*MockCollectionStore)(nil).SetRackSlotPosition), ctx, collectionID, deviceIdentifier, row, column, orgID)
}

// SoftDeleteCollection mocks base method.
func (m *MockCollectionStore) SoftDeleteCollection(ctx context.Context, orgID, collectionID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteCollection", ctx, orgID, collectionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteCollection indicates an expected call of SoftDeleteCollection.
func (mr *MockCollectionStoreMockRecorder) SoftDeleteCollection(ctx, orgID, collectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteCollection", reflect.TypeOf((*MockCollectionStore)(nil).SoftDeleteCollection), ctx, orgID, collectionID)
}

// UnassignDeviceSitesByRack mocks base method.
func (m *MockCollectionStore) UnassignDeviceSitesByRack(ctx context.Context, collectionID, orgID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignDeviceSitesByRack", ctx, collectionID, orgID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignDeviceSitesByRack indicates an expected call of UnassignDeviceSitesByRack.
func (mr *MockCollectionStoreMockRecorder) UnassignDeviceSitesByRack(ctx, collectionID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignDeviceSitesByRack", reflect.TypeOf((*MockCollectionStore)(nil).UnassignDeviceSitesByRack), ctx, collectionID, orgID)
}

// UpdateCollection mocks base method.
func (m *MockCollectionStore) UpdateCollection(ctx context.Context, orgID, collectionID int64, label, description *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCollection", ctx, orgID, collectionID, label, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCollection indicates an expected call of UpdateCollection.
func (mr *MockCollectionStoreMockRecorder) UpdateCollection(ctx, orgID, collectionID, label, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCollection", reflect.TypeOf((*MockCollectionStore)(nil).UpdateCollection), ctx, orgID, collectionID, label, description)
}

// UpdateRackInfo mocks base method.
func (m *MockCollectionStore) UpdateRackInfo(ctx context.Context, collectionID int64, zone string, rows, columns, orderIndex, coolingType int32, orgID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRackInfo", ctx, collectionID, zone, rows, columns, orderIndex, coolingType, orgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRackInfo indicates an expected call of UpdateRackInfo.
func (mr *MockCollectionStoreMockRecorder) UpdateRackInfo(ctx, collectionID, zone, rows, columns, orderIndex, coolingType, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRackInfo", reflect.TypeOf((*MockCollectionStore)(nil).UpdateRackInfo), ctx, collectionID, zone, rows, columns, orderIndex, coolingType, orgID)
}

// UpdateRackPlacement mocks base method.
func (m *MockCollectionStore) UpdateRackPlacement(ctx context.Context, collectionID, orgID int64, siteID, buildingID *int64, zone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRackPlacement", ctx, collectionID, orgID, siteID, buildingID, zone)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRackPlacement indicates an expected call of UpdateRackPlacement.
func (mr *MockCollectionStoreMockRecorder) UpdateRackPlacement(ctx, collectionID, orgID, siteID, buildingID, zone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRackPlacement", reflect.TypeOf((*MockCollectionStore)(nil).UpdateRackPlacement), ctx, collectionID, orgID, siteID, buildingID, zone)
}
