// Code generated by MockGen. DO NOT EDIT.
// Source: building.go
//
// Generated by this command:
//
//	mockgen -source=building.go -destination=mocks/mock_building_store.go -package=mocks BuildingStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/block/proto-fleet/server/internal/domain/buildings/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBuildingStore is a mock of BuildingStore interface.
type MockBuildingStore struct {
	ctrl     *gomock.Controller
	recorder *MockBuildingStoreMockRecorder
	isgomock struct{}
}

// MockBuildingStoreMockRecorder is the mock recorder for MockBuildingStore.
type MockBuildingStoreMockRecorder struct {
	mock *MockBuildingStore
}

// NewMockBuildingStore creates a new mock instance.
func NewMockBuildingStore(ctrl *gomock.Controller) *MockBuildingStore {
	mock := &MockBuildingStore{ctrl: ctrl}
	mock.recorder = &MockBuildingStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildingStore) EXPECT() *MockBuildingStoreMockRecorder {
	return m.recorder
}

// BuildingBelongsToOrg mocks base method.
func (m *MockBuildingStore) BuildingBelongsToOrg(ctx context.Context, orgID, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildingBelongsToOrg", ctx, orgID, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildingBelongsToOrg indicates an expected call of BuildingBelongsToOrg.
func (mr *MockBuildingStoreMockRecorder) BuildingBelongsToOrg(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildingBelongsToOrg", reflect.TypeOf((*MockBuildingStore)(nil).BuildingBelongsToOrg), ctx, orgID, id)
}

// BuildingsByIDs mocks base method.
func (m *MockBuildingStore) BuildingsByIDs(ctx context.Context, orgID int64, ids []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildingsByIDs", ctx, orgID, ids)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildingsByIDs indicates an expected call of BuildingsByIDs.
func (mr *MockBuildingStoreMockRecorder) BuildingsByIDs(ctx, orgID, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildingsByIDs", reflect.TypeOf((*MockBuildingStore)(nil).BuildingsByIDs), ctx, orgID, ids)
}

// CreateBuilding mocks base method.
func (m *MockBuildingStore) CreateBuilding(ctx context.Context, params models.CreateParams) (*models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBuilding", ctx, params)
	ret0, _ := ret[0].(*models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBuilding indicates an expected call of CreateBuilding.
func (mr *MockBuildingStoreMockRecorder) CreateBuilding(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBuilding", reflect.TypeOf((*MockBuildingStore)(nil).CreateBuilding), ctx, params)
}

// GetBuilding mocks base method.
func (m *MockBuildingStore) GetBuilding(ctx context.Context, orgID, id int64) (*models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuilding", ctx, orgID, id)
	ret0, _ := ret[0].(*models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuilding indicates an expected call of GetBuilding.
func (mr *MockBuildingStoreMockRecorder) GetBuilding(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuilding", reflect.TypeOf((*MockBuildingStore)(nil).GetBuilding), ctx, orgID, id)
}

// ListBuildings mocks base method.
func (m *MockBuildingStore) ListBuildings(ctx context.Context, filter models.ListFilter) ([]models.BuildingWithCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBuildings", ctx, filter)
	ret0, _ := ret[0].([]models.BuildingWithCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBuildings indicates an expected call of ListBuildings.
func (mr *MockBuildingStoreMockRecorder) ListBuildings(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBuildings", reflect.TypeOf((*MockBuildingStore)(nil).ListBuildings), ctx, filter)
}

// SoftDeleteBuilding mocks base method.
func (m *MockBuildingStore) SoftDeleteBuilding(ctx context.Context, orgID, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteBuilding", ctx, orgID, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteBuilding indicates an expected call of SoftDeleteBuilding.
func (mr *MockBuildingStoreMockRecorder) SoftDeleteBuilding(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteBuilding", reflect.TypeOf((*MockBuildingStore)(nil).SoftDeleteBuilding), ctx, orgID, id)
}

// UnassignRacksFromBuilding mocks base method.
func (m *MockBuildingStore) UnassignRacksFromBuilding(ctx context.Context, orgID, buildingID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignRacksFromBuilding", ctx, orgID, buildingID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignRacksFromBuilding indicates an expected call of UnassignRacksFromBuilding.
func (mr *MockBuildingStoreMockRecorder) UnassignRacksFromBuilding(ctx, orgID, buildingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignRacksFromBuilding", reflect.TypeOf((*MockBuildingStore)(nil).UnassignRacksFromBuilding), ctx, orgID, buildingID)
}

// UpdateBuilding mocks base method.
func (m *MockBuildingStore) UpdateBuilding(ctx context.Context, params models.UpdateParams) (*models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBuilding", ctx, params)
	ret0, _ := ret[0].(*models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBuilding indicates an expected call of UpdateBuilding.
func (mr *MockBuildingStoreMockRecorder) UpdateBuilding(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBuilding", reflect.TypeOf((*MockBuildingStore)(nil).UpdateBuilding), ctx, params)
}
