// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=mocks/mock_user_store.go -package=mocks UserStore UserManagementStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	interfaces "github.com/block/proto-fleet/server/internal/domain/stores/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockUserStore is a mock of UserStore interface.
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
	isgomock struct{}
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore.
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance.
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// CreateAdminUserWithOrganization mocks base method.
func (m *MockUserStore) CreateAdminUserWithOrganization(ctx context.Context, userID, username, passwordHash, orgName, orgID, minerAuthPrivateKey, roleName, roleDescription string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminUserWithOrganization", ctx, userID, username, passwordHash, orgName, orgID, minerAuthPrivateKey, roleName, roleDescription)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAdminUserWithOrganization indicates an expected call of CreateAdminUserWithOrganization.
func (mr *MockUserStoreMockRecorder) CreateAdminUserWithOrganization(ctx, userID, username, passwordHash, orgName, orgID, minerAuthPrivateKey, roleName, roleDescription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminUserWithOrganization", reflect.TypeOf((*MockUserStore)(nil).CreateAdminUserWithOrganization), ctx, userID, username, passwordHash, orgName, orgID, minerAuthPrivateKey, roleName, roleDescription)
}

// GetOrganizationPrivateKey mocks base method.
func (m *MockUserStore) GetOrganizationPrivateKey(ctx context.Context, orgID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationPrivateKey", ctx, orgID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationPrivateKey indicates an expected call of GetOrganizationPrivateKey.
func (mr *MockUserStoreMockRecorder) GetOrganizationPrivateKey(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationPrivateKey", reflect.TypeOf((*MockUserStore)(nil).GetOrganizationPrivateKey), ctx, orgID)
}

// GetOrganizationsForUser mocks base method.
func (m *MockUserStore) GetOrganizationsForUser(ctx context.Context, userID int64) ([]interfaces.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationsForUser", ctx, userID)
	ret0, _ := ret[0].([]interfaces.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationsForUser indicates an expected call of GetOrganizationsForUser.
func (mr *MockUserStoreMockRecorder) GetOrganizationsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationsForUser", reflect.TypeOf((*MockUserStore)(nil).GetOrganizationsForUser), ctx, userID)
}

// GetUserByExternalID mocks base method.
func (m *MockUserStore) GetUserByExternalID(ctx context.Context, userID string) (interfaces.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByExternalID", ctx, userID)
	ret0, _ := ret[0].(interfaces.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByExternalID indicates an expected call of GetUserByExternalID.
func (mr *MockUserStoreMockRecorder) GetUserByExternalID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByExternalID", reflect.TypeOf((*MockUserStore)(nil).GetUserByExternalID), ctx, userID)
}

// GetUserByID mocks base method.
func (m *MockUserStore) GetUserByID(ctx context.Context, userID int64) (interfaces.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(interfaces.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserStoreMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserStore)(nil).GetUserByID), ctx, userID)
}

// GetUserByIDForUpdate mocks base method.
func (m *MockUserStore) GetUserByIDForUpdate(ctx context.Context, userID int64) (interfaces.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByIDForUpdate", ctx, userID)
	ret0, _ := ret[0].(interfaces.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByIDForUpdate indicates an expected call of GetUserByIDForUpdate.
func (mr *MockUserStoreMockRecorder) GetUserByIDForUpdate(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByIDForUpdate", reflect.TypeOf((*MockUserStore)(nil).GetUserByIDForUpdate), ctx, userID)
}

// GetUserByUsername mocks base method.
func (m *MockUserStore) GetUserByUsername(ctx context.Context, username string) (interfaces.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(interfaces.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserStoreMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserStore)(nil).GetUserByUsername), ctx, username)
}

// HasUser mocks base method.
func (m *MockUserStore) HasUser(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasUser", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasUser indicates an expected call of HasUser.
func (mr *MockUserStoreMockRecorder) HasUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasUser", reflect.TypeOf((*MockUserStore)(nil).HasUser), ctx)
}

// PasswordUpdatedAt mocks base method.
func (m *MockUserStore) PasswordUpdatedAt(ctx context.Context, userID int64) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordUpdatedAt", ctx, userID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasswordUpdatedAt indicates an expected call of PasswordUpdatedAt.
func (mr *MockUserStoreMockRecorder) PasswordUpdatedAt(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordUpdatedAt", reflect.TypeOf((*MockUserStore)(nil).PasswordUpdatedAt), ctx, userID)
}

// UpdateUserPassword mocks base method.
func (m *MockUserStore) UpdateUserPassword(ctx context.Context, userID int64, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, userID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockUserStoreMockRecorder) UpdateUserPassword(ctx, userID, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockUserStore)(nil).UpdateUserPassword), ctx, userID, passwordHash)
}

// UpdateUserUsername mocks base method.
func (m *MockUserStore) UpdateUserUsername(ctx context.Context, userID int64, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserUsername", ctx, userID, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserUsername indicates an expected call of UpdateUserUsername.
func (mr *MockUserStoreMockRecorder) UpdateUserUsername(ctx, userID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserUsername", reflect.TypeOf((*MockUserStore)(nil).UpdateUserUsername), ctx, userID, username)
}

// MockUserManagementStore is a mock of UserManagementStore interface.
type MockUserManagementStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserManagementStoreMockRecorder
	isgomock struct{}
}

// MockUserManagementStoreMockRecorder is the mock recorder for MockUserManagementStore.
type MockUserManagementStoreMockRecorder struct {
	mock *MockUserManagementStore
}

// NewMockUserManagementStore creates a new mock instance.
func NewMockUserManagementStore(ctrl *gomock.Controller) *MockUserManagementStore {
	mock := &MockUserManagementStore{ctrl: ctrl}
	mock.recorder = &MockUserManagementStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserManagementStore) EXPECT() *MockUserManagementStoreMockRecorder {
	return m.recorder
}

// AdminResetUserPassword mocks base method.
func (m *MockUserManagementStore) AdminResetUserPassword(ctx context.Context, userID int64, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminResetUserPassword", ctx, userID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminResetUserPassword indicates an expected call of AdminResetUserPassword.
func (mr *MockUserManagementStoreMockRecorder) AdminResetUserPassword(ctx, userID, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminResetUserPassword", reflect.TypeOf((*MockUserManagementStore)(nil).AdminResetUserPassword), ctx, userID, passwordHash)
}

// CreateUser mocks base method.
func (m *MockUserManagementStore) CreateUser(ctx context.Context, externalUserID, username, passwordHash string, requiresPasswordChange bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, externalUserID, username, passwordHash, requiresPasswordChange)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserManagementStoreMockRecorder) CreateUser(ctx, externalUserID, username, passwordHash, requiresPasswordChange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserManagementStore)(nil).CreateUser), ctx, externalUserID, username, passwordHash, requiresPasswordChange)
}

// CreateUserOrganizationRole mocks base method.
func (m *MockUserManagementStore) CreateUserOrganizationRole(ctx context.Context, userID, organizationID, roleID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserOrganizationRole", ctx, userID, organizationID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserOrganizationRole indicates an expected call of CreateUserOrganizationRole.
func (mr *MockUserManagementStoreMockRecorder) CreateUserOrganizationRole(ctx, userID, organizationID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserOrganizationRole", reflect.TypeOf((*MockUserManagementStore)(nil).CreateUserOrganizationRole), ctx, userID, organizationID, roleID)
}

// GetBuiltinRoleForOrg mocks base method.
func (m *MockUserManagementStore) GetBuiltinRoleForOrg(ctx context.Context, organizationID int64, builtinKey string) (interfaces.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuiltinRoleForOrg", ctx, organizationID, builtinKey)
	ret0, _ := ret[0].(interfaces.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuiltinRoleForOrg indicates an expected call of GetBuiltinRoleForOrg.
func (mr *MockUserManagementStoreMockRecorder) GetBuiltinRoleForOrg(ctx, organizationID, builtinKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuiltinRoleForOrg", reflect.TypeOf((*MockUserManagementStore)(nil).GetBuiltinRoleForOrg), ctx, organizationID, builtinKey)
}

// GetUserRoleName mocks base method.
func (m *MockUserManagementStore) GetUserRoleName(ctx context.Context, userID, organizationID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoleName", ctx, userID, organizationID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoleName indicates an expected call of GetUserRoleName.
func (mr *MockUserManagementStoreMockRecorder) GetUserRoleName(ctx, userID, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoleName", reflect.TypeOf((*MockUserManagementStore)(nil).GetUserRoleName), ctx, userID, organizationID)
}

// ListPermissionKeysByRoleID mocks base method.
func (m *MockUserManagementStore) ListPermissionKeysByRoleID(ctx context.Context, roleID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissionKeysByRoleID", ctx, roleID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissionKeysByRoleID indicates an expected call of ListPermissionKeysByRoleID.
func (mr *MockUserManagementStoreMockRecorder) ListPermissionKeysByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissionKeysByRoleID", reflect.TypeOf((*MockUserManagementStore)(nil).ListPermissionKeysByRoleID), ctx, roleID)
}

// ListUsersForOrganization mocks base method.
func (m *MockUserManagementStore) ListUsersForOrganization(ctx context.Context, organizationID int64) ([]interfaces.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersForOrganization", ctx, organizationID)
	ret0, _ := ret[0].([]interfaces.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersForOrganization indicates an expected call of ListUsersForOrganization.
func (mr *MockUserManagementStoreMockRecorder) ListUsersForOrganization(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersForOrganization", reflect.TypeOf((*MockUserManagementStore)(nil).ListUsersForOrganization), ctx, organizationID)
}

// SoftDeleteUser mocks base method.
func (m *MockUserManagementStore) SoftDeleteUser(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteUser indicates an expected call of SoftDeleteUser.
func (mr *MockUserManagementStoreMockRecorder) SoftDeleteUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteUser", reflect.TypeOf((*MockUserManagementStore)(nil).SoftDeleteUser), ctx, userID)
}

// UpdateLastLogin mocks base method.
func (m *MockUserManagementStore) UpdateLastLogin(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockUserManagementStoreMockRecorder) UpdateLastLogin(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockUserManagementStore)(nil).UpdateLastLogin), ctx, userID)
}

// UpdateUserPasswordAndClearPasswordChangeFlag mocks base method.
func (m *MockUserManagementStore) UpdateUserPasswordAndClearPasswordChangeFlag(ctx context.Context, userID int64, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPasswordAndClearPasswordChangeFlag", ctx, userID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPasswordAndClearPasswordChangeFlag indicates an expected call of UpdateUserPasswordAndClearPasswordChangeFlag.
func (mr *MockUserManagementStoreMockRecorder) UpdateUserPasswordAndClearPasswordChangeFlag(ctx, userID, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPasswordAndClearPasswordChangeFlag", reflect.TypeOf((*MockUserManagementStore)(nil).UpdateUserPasswordAndClearPasswordChangeFlag), ctx, userID, passwordHash)
}
