-- Scope the curtailment idempotency / external-reference partial unique
-- indexes to non-terminal events only. Before this migration, a webhook
-- delivery that reused a long-completed event's idempotency_key (or
-- external_source+reference pair) returned that historical row from the
-- replay lookup with no new dispatch fired — the operator believed
-- curtailment was in flight, but the original event ended at some prior
-- time. Tightening the index frees the key once the event reaches a
-- terminal state, so subsequent calls treat the key as fresh.
--
-- Webhook retries during an event's in-flight lifetime still hit the
-- replay path (the partial index still covers pending/active/restoring
-- rows). Retries AFTER completion fire a fresh Start.
--
-- Keep each CONCURRENTLY operation in its own migration version. The
-- golang-migrate postgres driver executes a migration file as one command
-- unless statement splitting is enabled, and PostgreSQL rejects concurrent
-- index operations in a multi-command transaction block.
--
-- Operator recovery if 000057 fails after this DROP: schema_migrations
-- stays dirty at v56 with no idempotency index. Drop any INVALID
-- `uq_curtailment_event_idempotency` residue, resolve duplicate
-- `(org_id, idempotency_key)` rows that block the scoped CREATE, then
-- `migrate force 56` and retry `migrate up`.
DROP INDEX CONCURRENTLY IF EXISTS uq_curtailment_event_idempotency;
