name: Generated code check

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  generated-code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Hermit
        uses: ./.github/actions/hermit-setup

      - name: Configure Go cache
        uses: ./.github/actions/go-cache-setup

      - name: Install dependencies
        run: just setup

      - name: Generate code
        run: just gen

      - name: Check if committed generated code is up-to-date
        run: >
          git diff --quiet || {
            echo -e "\033[0;31mNewly generated code does not match the committed code. Run 'just gen', then commit and push the changes.\033[0m" 1>&2;
            echo -e "\n\n";
            git diff --exit-code
          }
