name: Proto Checks

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/protofleet-proto-checks.yml"
      - ".github/actions/hermit-setup/action.yml"
      - "buf.lock"
      - "buf.yaml"
      - "bin/hermit.hcl"
      - "hermit-packages/**"
      - "proto/**"
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  proto-lint:
    name: Protobuf Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Hermit
        uses: ./.github/actions/hermit-setup

      - name: Lint protobuf definitions
        run: buf lint
