// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"

	sitesv1 "github.com/block/proto-fleet/server/generated/grpc/sites/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedSitesCommand() *cli.Command {
	return &cli.Command{
		Name:  "sites",
		Usage: "Manage sites commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"assign-buildings",
				"Assign buildings to site",
				"/sites.v1.SiteService/AssignBuildingsToSite",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringSliceFlag{Name: "building-ids", Usage: "(required) building ids", Required: true},
					&cli.Int64Flag{Name: "target-site-id", Usage: "(required) target site id", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &sitesv1.AssignBuildingsToSiteRequest{}
					if cmd.IsSet("building-ids") {
						values, err := parseInt64Slice(cmd.StringSlice("building-ids"))
						if err != nil {
							return nil, err
						}
						req.BuildingIds = values
					}
					if cmd.IsSet("target-site-id") {
						value := cmd.Int64("target-site-id")
						req.TargetSiteId = &value
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &sitesv1.AssignBuildingsToSiteResponse{} },
			),
			generatedRequestCommand(
				"assign-devices",
				"Assign devices to site",
				"/sites.v1.SiteService/AssignDevicesToSite",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "target-site-id", Usage: "(required) target site id", Required: true},
					&cli.StringSliceFlag{Name: "device-identifiers", Usage: "(required) device identifiers", Required: true},
					&cli.BoolFlag{Name: "force-clear-conflicting-rack-membership", Usage: "force clear conflicting rack membership"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &sitesv1.AssignDevicesToSiteRequest{}
					if cmd.IsSet("target-site-id") {
						value := cmd.Int64("target-site-id")
						req.TargetSiteId = &value
					}
					if cmd.IsSet("device-identifiers") {
						req.DeviceIdentifiers = cmd.StringSlice("device-identifiers")
					}
					if cmd.IsSet("force-clear-conflicting-rack-membership") {
						value := cmd.Bool("force-clear-conflicting-rack-membership")
						req.ForceClearConflictingRackMembership = &value
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &sitesv1.AssignDevicesToSiteResponse{} },
			),
			generatedRequestCommand(
				"assign-racks",
				"Assign racks to site",
				"/sites.v1.SiteService/AssignRacksToSite",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringSliceFlag{Name: "rack-ids", Usage: "(required) rack ids", Required: true},
					&cli.Int64Flag{Name: "target-site-id", Usage: "(required) target site id", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &sitesv1.AssignRacksToSiteRequest{}
					if cmd.IsSet("rack-ids") {
						values, err := parseInt64Slice(cmd.StringSlice("rack-ids"))
						if err != nil {
							return nil, err
						}
						req.RackIds = values
					}
					if cmd.IsSet("target-site-id") {
						value := cmd.Int64("target-site-id")
						req.TargetSiteId = &value
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &sitesv1.AssignRacksToSiteResponse{} },
			),
			generatedRequestCommand(
				"create",
				"Create site",
				"/sites.v1.SiteService/CreateSite",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "name", Usage: "(required) name", Required: true},
					&cli.StringFlag{Name: "location-city", Usage: "location city"},
					&cli.StringFlag{Name: "location-state", Usage: "location state"},
					&cli.StringFlag{Name: "timezone", Usage: "timezone"},
					&cli.Float64Flag{Name: "power-capacity-mw", Usage: "power capacity mw"},
					&cli.StringFlag{Name: "network-config", Usage: "network config"},
					&cli.StringFlag{Name: "address", Usage: "address"},
					&cli.StringFlag{Name: "postal-code", Usage: "postal code"},
					&cli.StringFlag{Name: "country", Usage: "country"},
					&cli.StringFlag{Name: "notes", Usage: "notes"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &sitesv1.CreateSiteRequest{}
					if cmd.IsSet("name") {
						req.Name = cmd.String("name")
					}
					if cmd.IsSet("location-city") {
						req.LocationCity = cmd.String("location-city")
					}
					if cmd.IsSet("location-state") {
						req.LocationState = cmd.String("location-state")
					}
					if cmd.IsSet("timezone") {
						req.Timezone = cmd.String("timezone")
					}
					if cmd.IsSet("power-capacity-mw") {
						req.PowerCapacityMw = cmd.Float64("power-capacity-mw")
					}
					if cmd.IsSet("network-config") {
						req.NetworkConfig = cmd.String("network-config")
					}
					if cmd.IsSet("address") {
						req.Address = cmd.String("address")
					}
					if cmd.IsSet("postal-code") {
						req.PostalCode = cmd.String("postal-code")
					}
					if cmd.IsSet("country") {
						req.Country = cmd.String("country")
					}
					if cmd.IsSet("notes") {
						req.Notes = cmd.String("notes")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &sitesv1.CreateSiteResponse{} },
			),
			generatedRequestCommand(
				"delete",
				"Delete site",
				"/sites.v1.SiteService/DeleteSite",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "id", Usage: "(required) id", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &sitesv1.DeleteSiteRequest{}
					if cmd.IsSet("id") {
						req.Id = cmd.Int64("id")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &sitesv1.DeleteSiteResponse{} },
			),
			generatedRequestCommand(
				"get-infrastructure-control-subnets",
				"Get commissioned infrastructure control subnets",
				"/sites.v1.SiteService/GetInfrastructureControlSubnets",
				generatedAuthSessionOnly,
				[]cli.Flag{
					&cli.Int64Flag{Name: "site-id", Usage: "(required) site id", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &sitesv1.GetInfrastructureControlSubnetsRequest{}
					if cmd.IsSet("site-id") {
						req.SiteId = cmd.Int64("site-id")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &sitesv1.GetInfrastructureControlSubnetsResponse{} },
			),
			generatedRequestCommand(
				"list",
				"List sites",
				"/sites.v1.SiteService/ListSites",
				generatedAuthAuthenticated,
				[]cli.Flag{},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &sitesv1.ListSitesRequest{}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &sitesv1.ListSitesResponse{} },
			),
			generatedRequestCommand(
				"resolve",
				"Resolve a site by slug",
				"/sites.v1.SiteService/ResolveSiteBySlug",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "slug", Usage: "(required) slug", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &sitesv1.ResolveSiteBySlugRequest{}
					if cmd.IsSet("slug") {
						req.Slug = cmd.String("slug")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &sitesv1.ResolveSiteBySlugResponse{} },
			),
			generatedRequestCommand(
				"set-infrastructure-control-subnets",
				"Replace commissioned infrastructure control subnets; omit all subnet flags to decommission",
				"/sites.v1.SiteService/SetInfrastructureControlSubnets",
				generatedAuthSessionOnly,
				[]cli.Flag{
					&cli.Int64Flag{Name: "site-id", Usage: "(required) site id", Required: true},
					&cli.StringSliceFlag{Name: "infrastructure-control-subnets", Usage: "infrastructure control subnets"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &sitesv1.SetInfrastructureControlSubnetsRequest{}
					if cmd.IsSet("site-id") {
						req.SiteId = cmd.Int64("site-id")
					}
					if cmd.IsSet("infrastructure-control-subnets") {
						req.InfrastructureControlSubnets = cmd.StringSlice("infrastructure-control-subnets")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &sitesv1.SetInfrastructureControlSubnetsResponse{} },
			),
			generatedRequestCommand(
				"stats",
				"Get site stats",
				"/sites.v1.SiteService/GetSiteStats",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "site-id", Usage: "(required) site id", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &sitesv1.GetSiteStatsRequest{}
					if cmd.IsSet("site-id") {
						req.SiteId = cmd.Int64("site-id")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &sitesv1.GetSiteStatsResponse{} },
			),
			generatedRequestCommand(
				"update",
				"Update site",
				"/sites.v1.SiteService/UpdateSite",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "id", Usage: "(required) id", Required: true},
					&cli.StringFlag{Name: "name", Usage: "(required) name", Required: true},
					&cli.StringFlag{Name: "location-city", Usage: "location city"},
					&cli.StringFlag{Name: "location-state", Usage: "location state"},
					&cli.StringFlag{Name: "timezone", Usage: "timezone"},
					&cli.Float64Flag{Name: "power-capacity-mw", Usage: "power capacity mw"},
					&cli.StringFlag{Name: "network-config", Usage: "network config"},
					&cli.StringFlag{Name: "address", Usage: "address"},
					&cli.StringFlag{Name: "postal-code", Usage: "postal code"},
					&cli.StringFlag{Name: "country", Usage: "country"},
					&cli.StringFlag{Name: "notes", Usage: "notes"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &sitesv1.UpdateSiteRequest{}
					if cmd.IsSet("id") {
						req.Id = cmd.Int64("id")
					}
					if cmd.IsSet("name") {
						req.Name = cmd.String("name")
					}
					if cmd.IsSet("location-city") {
						req.LocationCity = cmd.String("location-city")
					}
					if cmd.IsSet("location-state") {
						req.LocationState = cmd.String("location-state")
					}
					if cmd.IsSet("timezone") {
						req.Timezone = cmd.String("timezone")
					}
					if cmd.IsSet("power-capacity-mw") {
						req.PowerCapacityMw = cmd.Float64("power-capacity-mw")
					}
					if cmd.IsSet("network-config") {
						req.NetworkConfig = cmd.String("network-config")
					}
					if cmd.IsSet("address") {
						req.Address = cmd.String("address")
					}
					if cmd.IsSet("postal-code") {
						req.PostalCode = cmd.String("postal-code")
					}
					if cmd.IsSet("country") {
						req.Country = cmd.String("country")
					}
					if cmd.IsSet("notes") {
						req.Notes = cmd.String("notes")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &sitesv1.UpdateSiteResponse{} },
			),
		},
	}
}
